// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
//
//lint:file-ignore SA1029 oapi-codegen emits string context keys for security scopes.
package httpapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionCookieScopes = "sessionCookie.Scopes"
)

// Defines values for CheckRunState.
const (
	CheckRunStateErrored CheckRunState = "errored"
	CheckRunStateFailed  CheckRunState = "failed"
	CheckRunStatePassed  CheckRunState = "passed"
	CheckRunStateQueued  CheckRunState = "queued"
	CheckRunStateRunning CheckRunState = "running"
	CheckRunStateTimeout CheckRunState = "timeout"
)

// Defines values for CheckRunDetailState.
const (
	CheckRunDetailStateErrored CheckRunDetailState = "errored"
	CheckRunDetailStateFailed  CheckRunDetailState = "failed"
	CheckRunDetailStatePassed  CheckRunDetailState = "passed"
	CheckRunDetailStateQueued  CheckRunDetailState = "queued"
	CheckRunDetailStateRunning CheckRunDetailState = "running"
	CheckRunDetailStateTimeout CheckRunDetailState = "timeout"
)

// Defines values for CheckRunDetailStepsStatus.
const (
	CheckRunDetailStepsStatusChanged     CheckRunDetailStepsStatus = "changed"
	CheckRunDetailStepsStatusFailed      CheckRunDetailStepsStatus = "failed"
	CheckRunDetailStepsStatusOk          CheckRunDetailStepsStatus = "ok"
	CheckRunDetailStepsStatusSkipped     CheckRunDetailStepsStatus = "skipped"
	CheckRunDetailStepsStatusUnreachable CheckRunDetailStepsStatus = "unreachable"
)

// Defines values for LabDeployStepStatus.
const (
	LabDeployStepStatusCompensated LabDeployStepStatus = "compensated"
	LabDeployStepStatusFailed      LabDeployStepStatus = "failed"
	LabDeployStepStatusInProgress  LabDeployStepStatus = "in_progress"
	LabDeployStepStatusPending     LabDeployStepStatus = "pending"
	LabDeployStepStatusSucceeded   LabDeployStepStatus = "succeeded"
)

// Defines values for LabDeployStepStepName.
const (
	AllocateProject  LabDeployStepStepName = "allocate_project"
	BootVm           LabDeployStepStepName = "boot_vm"
	CreateKeypair    LabDeployStepStepName = "create_keypair"
	InitialCheck     LabDeployStepStepName = "initial_check"
	ProvisionNetwork LabDeployStepStepName = "provision_network"
	WaitSsh          LabDeployStepStepName = "wait_ssh"
)

// Defines values for LabState.
const (
	LabStateChecking       LabState = "checking"
	LabStateCleaning       LabState = "cleaning"
	LabStateDeploying      LabState = "deploying"
	LabStateDone           LabState = "done"
	LabStateFailed         LabState = "failed"
	LabStateFrozen         LabState = "frozen"
	LabStatePendingProject LabState = "pending_project"
	LabStatePendingQuota   LabState = "pending_quota"
	LabStateReady          LabState = "ready"
	LabStateRejected       LabState = "rejected"
)

// Defines values for ProjectState.
const (
	ProjectStateAllocated      ProjectState = "allocated"
	ProjectStateCleaning       ProjectState = "cleaning"
	ProjectStateDecommissioned ProjectState = "decommissioned"
	ProjectStateFree           ProjectState = "free"
	ProjectStateQuarantine     ProjectState = "quarantine"
)

// Defines values for SettingScope.
const (
	SettingScopeGlobal         SettingScope = "global"
	SettingScopePerCourse      SettingScope = "per_course"
	SettingScopePerLabTemplate SettingScope = "per_lab_template"
)

// Defines values for SettingUpdateScope.
const (
	SettingUpdateScopeGlobal         SettingUpdateScope = "global"
	SettingUpdateScopePerCourse      SettingUpdateScope = "per_course"
	SettingUpdateScopePerLabTemplate SettingUpdateScope = "per_lab_template"
)

// Defines values for UserMeCoursesRoleInCourse.
const (
	UserMeCoursesRoleInCourseLearner UserMeCoursesRoleInCourse = "learner"
	UserMeCoursesRoleInCourseTeacher UserMeCoursesRoleInCourse = "teacher"
)

// Defines values for UserMeRole.
const (
	UserMeRoleAdmin   UserMeRole = "admin"
	UserMeRoleStudent UserMeRole = "student"
	UserMeRoleTeacher UserMeRole = "teacher"
)

// Defines values for GetAdminSettingsParamsScope.
const (
	Global         GetAdminSettingsParamsScope = "global"
	PerCourse      GetAdminSettingsParamsScope = "per_course"
	PerLabTemplate GetAdminSettingsParamsScope = "per_lab_template"
)

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	ActorUserId *openapi_types.UUID `json:"actor_user_id"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Kind        *string             `json:"kind,omitempty"`
	OccurredAt  *time.Time          `json:"occurred_at,omitempty"`
	Payload     *interface{}        `json:"payload,omitempty"`
	RequestId   *string             `json:"request_id"`
	SubjectId   *openapi_types.UUID `json:"subject_id"`
	SubjectType *string             `json:"subject_type,omitempty"`
}

// CheckRun defines model for CheckRun.
type CheckRun struct {
	CheckTemplateId *openapi_types.UUID `json:"check_template_id,omitempty"`
	FinishedAt      *time.Time          `json:"finished_at"`
	Id              *openapi_types.UUID `json:"id,omitempty"`
	LabInstanceId   *openapi_types.UUID `json:"lab_instance_id,omitempty"`
	StartedAt       *time.Time          `json:"started_at"`
	State           *CheckRunState      `json:"state,omitempty"`
	Summary         *string             `json:"summary"`
}

// CheckRunState defines model for CheckRun.State.
type CheckRunState string

// CheckRunDetail defines model for CheckRunDetail.
type CheckRunDetail struct {
	AnsibleStdout   *string              `json:"ansible_stdout,omitempty"`
	CheckTemplateId *openapi_types.UUID  `json:"check_template_id,omitempty"`
	FinishedAt      *time.Time           `json:"finished_at"`
	Id              *openapi_types.UUID  `json:"id,omitempty"`
	LabInstanceId   *openapi_types.UUID  `json:"lab_instance_id,omitempty"`
	StartedAt       *time.Time           `json:"started_at"`
	State           *CheckRunDetailState `json:"state,omitempty"`
	Steps           *[]struct {
		Actual   *interface{}               `json:"actual,omitempty"`
		Expected *interface{}               `json:"expected,omitempty"`
		Message  *string                    `json:"message,omitempty"`
		Status   *CheckRunDetailStepsStatus `json:"status,omitempty"`
		TaskName *string                    `json:"task_name,omitempty"`
	} `json:"steps,omitempty"`
	Summary *string `json:"summary"`
}

// CheckRunDetailState defines model for CheckRunDetail.State.
type CheckRunDetailState string

// CheckRunDetailStepsStatus defines model for CheckRunDetail.Steps.Status.
type CheckRunDetailStepsStatus string

// LabDeployStep defines model for LabDeployStep.
type LabDeployStep struct {
	Attempt    *int                   `json:"attempt,omitempty"`
	FinishedAt *time.Time             `json:"finished_at"`
	LastError  *string                `json:"last_error"`
	StartedAt  *time.Time             `json:"started_at"`
	Status     *LabDeployStepStatus   `json:"status,omitempty"`
	StepName   *LabDeployStepStepName `json:"step_name,omitempty"`
}

// LabDeployStepStatus defines model for LabDeployStep.Status.
type LabDeployStepStatus string

// LabDeployStepStepName defines model for LabDeployStep.StepName.
type LabDeployStepStepName string

// LabInstance defines model for LabInstance.
type LabInstance struct {
	CleanupAt     *time.Time          `json:"cleanup_at"`
	CourseId      openapi_types.UUID  `json:"course_id"`
	CreatedAt     time.Time           `json:"created_at"`
	Id            openapi_types.UUID  `json:"id"`
	LabTemplateId openapi_types.UUID  `json:"lab_template_id"`
	ProjectId     *openapi_types.UUID `json:"project_id"`
	State         LabState            `json:"state"`
	StateReason   *string             `json:"state_reason"`
	StudentUserId openapi_types.UUID  `json:"student_user_id"`
	UnfreezeAt    *time.Time          `json:"unfreeze_at"`
	UpdatedAt     *time.Time          `json:"updated_at,omitempty"`
}

// LabInstanceDetail defines model for LabInstanceDetail.
type LabInstanceDetail struct {
	CleanupAt   *time.Time         `json:"cleanup_at"`
	CourseId    openapi_types.UUID `json:"course_id"`
	CreatedAt   time.Time          `json:"created_at"`
	DeploySteps *[]LabDeployStep   `json:"deploy_steps,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	KiResources *struct {
		FloatingIps *[]string `json:"floating_ips,omitempty"`
		NetworkId   *string   `json:"network_id,omitempty"`
		ServerIds   *[]string `json:"server_ids,omitempty"`
	} `json:"ki_resources,omitempty"`
	LabTemplateId  openapi_types.UUID  `json:"lab_template_id"`
	LatestCheckRun *CheckRun           `json:"latest_check_run,omitempty"`
	ProjectId      *openapi_types.UUID `json:"project_id"`
	State          LabState            `json:"state"`
	StateReason    *string             `json:"state_reason"`
	StudentUserId  openapi_types.UUID  `json:"student_user_id"`
	UnfreezeAt     *time.Time          `json:"unfreeze_at"`
	UpdatedAt      *time.Time          `json:"updated_at,omitempty"`
}

// LabState defines model for LabState.
type LabState string

// Problem RFC 7807 problem details
type Problem struct {
	// Code Stable error code, e.g. ERR_QUOTA_EXCEEDED
	Code     *string `json:"code,omitempty"`
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// Project defines model for Project.
type Project struct {
	AllocatedToLabId  *openapi_types.UUID `json:"allocated_to_lab_id"`
	CleanupFailures   *int                `json:"cleanup_failures,omitempty"`
	Id                *openapi_types.UUID `json:"id,omitempty"`
	KiDomainId        *string             `json:"ki_domain_id,omitempty"`
	KiProjectId       *string             `json:"ki_project_id,omitempty"`
	LastStateChangeAt *time.Time          `json:"last_state_change_at,omitempty"`
	Name              *string             `json:"name,omitempty"`
	State             *ProjectState       `json:"state,omitempty"`
}

// ProjectState defines model for ProjectState.
type ProjectState string

// QuotaSnapshot defines model for QuotaSnapshot.
type QuotaSnapshot struct {
	Disk           *Resource  `json:"disk,omitempty"`
	FetchedAt      *time.Time `json:"fetched_at,omitempty"`
	Ram            *Resource  `json:"ram,omitempty"`
	ThresholdPct   *float32   `json:"threshold_pct,omitempty"`
	UtilizationPct *struct {
		Disk *float32 `json:"disk,omitempty"`

		// Max max of all three, used for threshold check
		Max   *float32 `json:"max,omitempty"`
		Ram   *float32 `json:"ram,omitempty"`
		Vcpus *float32 `json:"vcpus,omitempty"`
	} `json:"utilization_pct,omitempty"`
	Vcpus *Resource `json:"vcpus,omitempty"`
}

// Resource defines model for Resource.
type Resource struct {
	Total *float32 `json:"total,omitempty"`
	Unit  *string  `json:"unit,omitempty"`
	Used  *float32 `json:"used,omitempty"`
}

// Setting defines model for Setting.
type Setting struct {
	Key             *string             `json:"key,omitempty"`
	Scope           *SettingScope       `json:"scope,omitempty"`
	ScopeId         *openapi_types.UUID `json:"scope_id"`
	UpdatedAt       *time.Time          `json:"updated_at,omitempty"`
	UpdatedByUserId *openapi_types.UUID `json:"updated_by_user_id,omitempty"`
	Value           *interface{}        `json:"value,omitempty"`
}

// SettingScope defines model for Setting.Scope.
type SettingScope string

// SettingUpdate defines model for SettingUpdate.
type SettingUpdate struct {
	Key     string              `json:"key"`
	Scope   SettingUpdateScope  `json:"scope"`
	ScopeId *openapi_types.UUID `json:"scope_id"`
	Value   interface{}         `json:"value"`
}

// SettingUpdateScope defines model for SettingUpdate.Scope.
type SettingUpdateScope string

// UserMe defines model for UserMe.
type UserMe struct {
	Courses *[]struct {
		Id           *openapi_types.UUID        `json:"id,omitempty"`
		Name         *string                    `json:"name,omitempty"`
		RoleInCourse *UserMeCoursesRoleInCourse `json:"role_in_course,omitempty"`
	} `json:"courses,omitempty"`
	DisplayName string             `json:"display_name"`
	Email       *string            `json:"email,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Role        UserMeRole         `json:"role"`
}

// UserMeCoursesRoleInCourse defines model for UserMe.Courses.RoleInCourse.
type UserMeCoursesRoleInCourse string

// UserMeRole defines model for UserMe.Role.
type UserMeRole string

// CheckId defines model for CheckId.
type CheckId = openapi_types.UUID

// LabId defines model for LabId.
type LabId = openapi_types.UUID

// Conflict RFC 7807 problem details
type Conflict = Problem

// Forbidden RFC 7807 problem details
type Forbidden = Problem

// NotFound RFC 7807 problem details
type NotFound = Problem

// Unauthorized RFC 7807 problem details
type Unauthorized = Problem

// GetAdminAuditParams defines parameters for GetAdminAudit.
type GetAdminAuditParams struct {
	Kind        *string             `form:"kind,omitempty" json:"kind,omitempty"`
	ActorUserId *openapi_types.UUID `form:"actor_user_id,omitempty" json:"actor_user_id,omitempty"`
	Since       *time.Time          `form:"since,omitempty" json:"since,omitempty"`
	Limit       *int                `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetAdminProjectsParams defines parameters for GetAdminProjects.
type GetAdminProjectsParams struct {
	KiDomainId *string       `form:"ki_domain_id,omitempty" json:"ki_domain_id,omitempty"`
	State      *ProjectState `form:"state,omitempty" json:"state,omitempty"`
}

// PostAdminProjectsIdQuarantineJSONBody defines parameters for PostAdminProjectsIdQuarantine.
type PostAdminProjectsIdQuarantineJSONBody struct {
	Reason string `json:"reason"`
}

// GetAdminSettingsParams defines parameters for GetAdminSettings.
type GetAdminSettingsParams struct {
	Scope   *GetAdminSettingsParamsScope `form:"scope,omitempty" json:"scope,omitempty"`
	ScopeId *openapi_types.UUID          `form:"scope_id,omitempty" json:"scope_id,omitempty"`
}

// GetAdminSettingsParamsScope defines parameters for GetAdminSettings.
type GetAdminSettingsParamsScope string

// PostAuthLoginJSONBody defines parameters for PostAuthLogin.
type PostAuthLoginJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// GetLabsParams defines parameters for GetLabs.
type GetLabsParams struct {
	CourseId *openapi_types.UUID `form:"course_id,omitempty" json:"course_id,omitempty"`
	State    *[]LabState         `form:"state,omitempty" json:"state,omitempty"`
}

// PostLabsJSONBody defines parameters for PostLabs.
type PostLabsJSONBody struct {
	CourseId      openapi_types.UUID `json:"course_id"`
	LabTemplateId openapi_types.UUID `json:"lab_template_id"`
}

// PostLabsIdChecksJSONBody defines parameters for PostLabsIdChecks.
type PostLabsIdChecksJSONBody struct {
	CheckTemplateId openapi_types.UUID `json:"check_template_id"`
}

// PostLabsIdExtendJSONBody defines parameters for PostLabsIdExtend.
type PostLabsIdExtendJSONBody struct {
	ExtendBySeconds int `json:"extend_by_seconds"`
}

// PostLabsIdFreezeJSONBody defines parameters for PostLabsIdFreeze.
type PostLabsIdFreezeJSONBody struct {
	// FreezeForSeconds Только teacher. Default — из Settings.
	FreezeForSeconds *int   `json:"freeze_for_seconds,omitempty"`
	Reason           string `json:"reason"`
}

// PostAdminProjectsIdQuarantineJSONRequestBody defines body for PostAdminProjectsIdQuarantine for application/json ContentType.
type PostAdminProjectsIdQuarantineJSONRequestBody PostAdminProjectsIdQuarantineJSONBody

// PutAdminSettingsJSONRequestBody defines body for PutAdminSettings for application/json ContentType.
type PutAdminSettingsJSONRequestBody = SettingUpdate

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody PostAuthLoginJSONBody

// PostLabsJSONRequestBody defines body for PostLabs for application/json ContentType.
type PostLabsJSONRequestBody PostLabsJSONBody

// PostLabsIdChecksJSONRequestBody defines body for PostLabsIdChecks for application/json ContentType.
type PostLabsIdChecksJSONRequestBody PostLabsIdChecksJSONBody

// PostLabsIdExtendJSONRequestBody defines body for PostLabsIdExtend for application/json ContentType.
type PostLabsIdExtendJSONRequestBody PostLabsIdExtendJSONBody

// PostLabsIdFreezeJSONRequestBody defines body for PostLabsIdFreeze for application/json ContentType.
type PostLabsIdFreezeJSONRequestBody PostLabsIdFreezeJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Аудит-лог
	// (GET /admin/audit)
	GetAdminAudit(w http.ResponseWriter, r *http.Request, params GetAdminAuditParams)
	// Состояние пула проектов
	// (GET /admin/projects)
	GetAdminProjects(w http.ResponseWriter, r *http.Request, params GetAdminProjectsParams)
	// Quarantine проекта (заблокировать от аренды)
	// (POST /admin/projects/{id}/quarantine)
	PostAdminProjectsIdQuarantine(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Manual release (вернуть в FREE после ручного cleanup)
	// (POST /admin/projects/{id}/release)
	PostAdminProjectsIdRelease(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Текущая утилизация КИ
	// (GET /admin/quota)
	GetAdminQuota(w http.ResponseWriter, r *http.Request)
	// Текущие настройки
	// (GET /admin/settings)
	GetAdminSettings(w http.ResponseWriter, r *http.Request, params GetAdminSettingsParams)
	// Обновить настройку (teacher/admin)
	// (PUT /admin/settings)
	PutAdminSettings(w http.ResponseWriter, r *http.Request)
	// Логин для teacher/admin (студенты — через LTI)
	// (POST /auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// Завершить сессию
	// (POST /auth/logout)
	PostAuthLogout(w http.ResponseWriter, r *http.Request)
	// Текущий пользователь
	// (GET /auth/me)
	GetAuthMe(w http.ResponseWriter, r *http.Request)
	// Детали запуска проверки (steps, stdout, summary)
	// (GET /checks/{id})
	GetChecksId(w http.ResponseWriter, r *http.Request, id CheckId)
	// Liveness probe
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// Список моих лаб (студент) или лаб курса (преподаватель)
	// (GET /labs)
	GetLabs(w http.ResponseWriter, r *http.Request, params GetLabsParams)
	// Запросить новый стенд
	// (POST /labs)
	PostLabs(w http.ResponseWriter, r *http.Request)
	// Завершить стенд (cleanup)
	// (DELETE /labs/{id})
	DeleteLabsId(w http.ResponseWriter, r *http.Request, id LabId)
	// Детали стенда
	// (GET /labs/{id})
	GetLabsId(w http.ResponseWriter, r *http.Request, id LabId)
	// История проверок стенда
	// (GET /labs/{id}/checks)
	GetLabsIdChecks(w http.ResponseWriter, r *http.Request, id LabId)
	// Запустить проверку
	// (POST /labs/{id}/checks)
	PostLabsIdChecks(w http.ResponseWriter, r *http.Request, id LabId)
	// Продлить cleanup_at (только teacher)
	// (POST /labs/{id}/extend)
	PostLabsIdExtend(w http.ResponseWriter, r *http.Request, id LabId)
	// Заморозить (студент — "сообщить о проблеме", teacher — manual freeze)
	// (POST /labs/{id}/freeze)
	PostLabsIdFreeze(w http.ResponseWriter, r *http.Request, id LabId)
	// Скачать свой приватный SSH-ключ (только owner)
	// (GET /labs/{id}/ssh-key)
	GetLabsIdSshKey(w http.ResponseWriter, r *http.Request, id LabId)
	// Снять заморозку (только teacher)
	// (POST /labs/{id}/unfreeze)
	PostLabsIdUnfreeze(w http.ResponseWriter, r *http.Request, id LabId)
	// Readiness probe (DB + Redis)
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
	// SSE-стрим обновлений лаб текущего пользователя
	// (GET /stream/labs)
	GetStreamLabs(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Аудит-лог
// (GET /admin/audit)
func (_ Unimplemented) GetAdminAudit(w http.ResponseWriter, r *http.Request, params GetAdminAuditParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Состояние пула проектов
// (GET /admin/projects)
func (_ Unimplemented) GetAdminProjects(w http.ResponseWriter, r *http.Request, params GetAdminProjectsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Quarantine проекта (заблокировать от аренды)
// (POST /admin/projects/{id}/quarantine)
func (_ Unimplemented) PostAdminProjectsIdQuarantine(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Manual release (вернуть в FREE после ручного cleanup)
// (POST /admin/projects/{id}/release)
func (_ Unimplemented) PostAdminProjectsIdRelease(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Текущая утилизация КИ
// (GET /admin/quota)
func (_ Unimplemented) GetAdminQuota(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Текущие настройки
// (GET /admin/settings)
func (_ Unimplemented) GetAdminSettings(w http.ResponseWriter, r *http.Request, params GetAdminSettingsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Обновить настройку (teacher/admin)
// (PUT /admin/settings)
func (_ Unimplemented) PutAdminSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Логин для teacher/admin (студенты — через LTI)
// (POST /auth/login)
func (_ Unimplemented) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Завершить сессию
// (POST /auth/logout)
func (_ Unimplemented) PostAuthLogout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Текущий пользователь
// (GET /auth/me)
func (_ Unimplemented) GetAuthMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Детали запуска проверки (steps, stdout, summary)
// (GET /checks/{id})
func (_ Unimplemented) GetChecksId(w http.ResponseWriter, r *http.Request, id CheckId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe
// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Список моих лаб (студент) или лаб курса (преподаватель)
// (GET /labs)
func (_ Unimplemented) GetLabs(w http.ResponseWriter, r *http.Request, params GetLabsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Запросить новый стенд
// (POST /labs)
func (_ Unimplemented) PostLabs(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Завершить стенд (cleanup)
// (DELETE /labs/{id})
func (_ Unimplemented) DeleteLabsId(w http.ResponseWriter, r *http.Request, id LabId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Детали стенда
// (GET /labs/{id})
func (_ Unimplemented) GetLabsId(w http.ResponseWriter, r *http.Request, id LabId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// История проверок стенда
// (GET /labs/{id}/checks)
func (_ Unimplemented) GetLabsIdChecks(w http.ResponseWriter, r *http.Request, id LabId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Запустить проверку
// (POST /labs/{id}/checks)
func (_ Unimplemented) PostLabsIdChecks(w http.ResponseWriter, r *http.Request, id LabId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Продлить cleanup_at (только teacher)
// (POST /labs/{id}/extend)
func (_ Unimplemented) PostLabsIdExtend(w http.ResponseWriter, r *http.Request, id LabId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Заморозить (студент — "сообщить о проблеме", teacher — manual freeze)
// (POST /labs/{id}/freeze)
func (_ Unimplemented) PostLabsIdFreeze(w http.ResponseWriter, r *http.Request, id LabId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Скачать свой приватный SSH-ключ (только owner)
// (GET /labs/{id}/ssh-key)
func (_ Unimplemented) GetLabsIdSshKey(w http.ResponseWriter, r *http.Request, id LabId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Снять заморозку (только teacher)
// (POST /labs/{id}/unfreeze)
func (_ Unimplemented) PostLabsIdUnfreeze(w http.ResponseWriter, r *http.Request, id LabId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Readiness probe (DB + Redis)
// (GET /readyz)
func (_ Unimplemented) GetReadyz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SSE-стрим обновлений лаб текущего пользователя
// (GET /stream/labs)
func (_ Unimplemented) GetStreamLabs(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAdminAudit operation middleware
func (siw *ServerInterfaceWrapper) GetAdminAudit(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAdminAuditParams

	// ------------- Optional query parameter "kind" -------------

	err = runtime.BindQueryParameter("form", true, false, "kind", r.URL.Query(), &params.Kind)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		return
	}

	// ------------- Optional query parameter "actor_user_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "actor_user_id", r.URL.Query(), &params.ActorUserId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "actor_user_id", Err: err})
		return
	}

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", r.URL.Query(), &params.Since)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminAudit(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetAdminProjects operation middleware
func (siw *ServerInterfaceWrapper) GetAdminProjects(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAdminProjectsParams

	// ------------- Optional query parameter "ki_domain_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "ki_domain_id", r.URL.Query(), &params.KiDomainId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ki_domain_id", Err: err})
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminProjects(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostAdminProjectsIdQuarantine operation middleware
func (siw *ServerInterfaceWrapper) PostAdminProjectsIdQuarantine(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAdminProjectsIdQuarantine(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostAdminProjectsIdRelease operation middleware
func (siw *ServerInterfaceWrapper) PostAdminProjectsIdRelease(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAdminProjectsIdRelease(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetAdminQuota operation middleware
func (siw *ServerInterfaceWrapper) GetAdminQuota(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminQuota(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetAdminSettings operation middleware
func (siw *ServerInterfaceWrapper) GetAdminSettings(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAdminSettingsParams

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", true, false, "scope", r.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "scope", Err: err})
		return
	}

	// ------------- Optional query parameter "scope_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "scope_id", r.URL.Query(), &params.ScopeId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "scope_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminSettings(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PutAdminSettings operation middleware
func (siw *ServerInterfaceWrapper) PutAdminSettings(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutAdminSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogout(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMe(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetChecksId operation middleware
func (siw *ServerInterfaceWrapper) GetChecksId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id CheckId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChecksId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetLabs operation middleware
func (siw *ServerInterfaceWrapper) GetLabs(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLabsParams

	// ------------- Optional query parameter "course_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "course_id", r.URL.Query(), &params.CourseId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "course_id", Err: err})
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLabs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostLabs operation middleware
func (siw *ServerInterfaceWrapper) PostLabs(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostLabs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteLabsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteLabsId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id LabId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteLabsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetLabsId operation middleware
func (siw *ServerInterfaceWrapper) GetLabsId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id LabId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLabsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetLabsIdChecks operation middleware
func (siw *ServerInterfaceWrapper) GetLabsIdChecks(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id LabId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLabsIdChecks(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostLabsIdChecks operation middleware
func (siw *ServerInterfaceWrapper) PostLabsIdChecks(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id LabId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostLabsIdChecks(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostLabsIdExtend operation middleware
func (siw *ServerInterfaceWrapper) PostLabsIdExtend(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id LabId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostLabsIdExtend(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostLabsIdFreeze operation middleware
func (siw *ServerInterfaceWrapper) PostLabsIdFreeze(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id LabId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostLabsIdFreeze(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetLabsIdSshKey operation middleware
func (siw *ServerInterfaceWrapper) GetLabsIdSshKey(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id LabId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLabsIdSshKey(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostLabsIdUnfreeze operation middleware
func (siw *ServerInterfaceWrapper) PostLabsIdUnfreeze(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id LabId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostLabsIdUnfreeze(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetStreamLabs operation middleware
func (siw *ServerInterfaceWrapper) GetStreamLabs(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStreamLabs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/audit", wrapper.GetAdminAudit)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/projects", wrapper.GetAdminProjects)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/projects/{id}/quarantine", wrapper.PostAdminProjectsIdQuarantine)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/projects/{id}/release", wrapper.PostAdminProjectsIdRelease)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/quota", wrapper.GetAdminQuota)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/settings", wrapper.GetAdminSettings)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/admin/settings", wrapper.PutAdminSettings)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.PostAuthLogout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetAuthMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/checks/{id}", wrapper.GetChecksId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/labs", wrapper.GetLabs)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/labs", wrapper.PostLabs)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/labs/{id}", wrapper.DeleteLabsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/labs/{id}", wrapper.GetLabsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/labs/{id}/checks", wrapper.GetLabsIdChecks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/labs/{id}/checks", wrapper.PostLabsIdChecks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/labs/{id}/extend", wrapper.PostLabsIdExtend)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/labs/{id}/freeze", wrapper.PostLabsIdFreeze)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/labs/{id}/ssh-key", wrapper.GetLabsIdSshKey)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/labs/{id}/unfreeze", wrapper.PostLabsIdUnfreeze)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadyz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stream/labs", wrapper.GetStreamLabs)
	})

	return r
}

type ConflictApplicationProblemPlusJSONResponse Problem

type ForbiddenApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type GetAdminAuditRequestObject struct {
	Params GetAdminAuditParams
}

type GetAdminAuditResponseObject interface {
	VisitGetAdminAuditResponse(w http.ResponseWriter) error
}

type GetAdminAudit200JSONResponse []AuditEvent

func (response GetAdminAudit200JSONResponse) VisitGetAdminAuditResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminProjectsRequestObject struct {
	Params GetAdminProjectsParams
}

type GetAdminProjectsResponseObject interface {
	VisitGetAdminProjectsResponse(w http.ResponseWriter) error
}

type GetAdminProjects200JSONResponse []Project

func (response GetAdminProjects200JSONResponse) VisitGetAdminProjectsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostAdminProjectsIdQuarantineRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *PostAdminProjectsIdQuarantineJSONRequestBody
}

type PostAdminProjectsIdQuarantineResponseObject interface {
	VisitPostAdminProjectsIdQuarantineResponse(w http.ResponseWriter) error
}

type PostAdminProjectsIdQuarantine200Response struct {
}

func (response PostAdminProjectsIdQuarantine200Response) VisitPostAdminProjectsIdQuarantineResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PostAdminProjectsIdReleaseRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type PostAdminProjectsIdReleaseResponseObject interface {
	VisitPostAdminProjectsIdReleaseResponse(w http.ResponseWriter) error
}

type PostAdminProjectsIdRelease200Response struct {
}

func (response PostAdminProjectsIdRelease200Response) VisitPostAdminProjectsIdReleaseResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetAdminQuotaRequestObject struct {
}

type GetAdminQuotaResponseObject interface {
	VisitGetAdminQuotaResponse(w http.ResponseWriter) error
}

type GetAdminQuota200JSONResponse QuotaSnapshot

func (response GetAdminQuota200JSONResponse) VisitGetAdminQuotaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminSettingsRequestObject struct {
	Params GetAdminSettingsParams
}

type GetAdminSettingsResponseObject interface {
	VisitGetAdminSettingsResponse(w http.ResponseWriter) error
}

type GetAdminSettings200JSONResponse []Setting

func (response GetAdminSettings200JSONResponse) VisitGetAdminSettingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutAdminSettingsRequestObject struct {
	Body *PutAdminSettingsJSONRequestBody
}

type PutAdminSettingsResponseObject interface {
	VisitPutAdminSettingsResponse(w http.ResponseWriter) error
}

type PutAdminSettings200JSONResponse Setting

func (response PutAdminSettings200JSONResponse) VisitPutAdminSettingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthLoginRequestObject struct {
	Body *PostAuthLoginJSONRequestBody
}

type PostAuthLoginResponseObject interface {
	VisitPostAuthLoginResponse(w http.ResponseWriter) error
}

type PostAuthLogin204Response struct {
}

func (response PostAuthLogin204Response) VisitPostAuthLoginResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PostAuthLogin401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response PostAuthLogin401ApplicationProblemPlusJSONResponse) VisitPostAuthLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthLogoutRequestObject struct {
}

type PostAuthLogoutResponseObject interface {
	VisitPostAuthLogoutResponse(w http.ResponseWriter) error
}

type PostAuthLogout204Response struct {
}

func (response PostAuthLogout204Response) VisitPostAuthLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetAuthMeRequestObject struct {
}

type GetAuthMeResponseObject interface {
	VisitGetAuthMeResponse(w http.ResponseWriter) error
}

type GetAuthMe200JSONResponse UserMe

func (response GetAuthMe200JSONResponse) VisitGetAuthMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAuthMe401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetAuthMe401ApplicationProblemPlusJSONResponse) VisitGetAuthMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetChecksIdRequestObject struct {
	Id CheckId `json:"id"`
}

type GetChecksIdResponseObject interface {
	VisitGetChecksIdResponse(w http.ResponseWriter) error
}

type GetChecksId200JSONResponse CheckRunDetail

func (response GetChecksId200JSONResponse) VisitGetChecksIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200Response struct {
}

func (response GetHealthz200Response) VisitGetHealthzResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetLabsRequestObject struct {
	Params GetLabsParams
}

type GetLabsResponseObject interface {
	VisitGetLabsResponse(w http.ResponseWriter) error
}

type GetLabs200JSONResponse []LabInstance

func (response GetLabs200JSONResponse) VisitGetLabsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostLabsRequestObject struct {
	Body *PostLabsJSONRequestBody
}

type PostLabsResponseObject interface {
	VisitPostLabsResponse(w http.ResponseWriter) error
}

type PostLabs201JSONResponse LabInstance

func (response PostLabs201JSONResponse) VisitPostLabsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostLabs409ApplicationProblemPlusJSONResponse struct {
	ConflictApplicationProblemPlusJSONResponse
}

func (response PostLabs409ApplicationProblemPlusJSONResponse) VisitPostLabsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type DeleteLabsIdRequestObject struct {
	Id LabId `json:"id"`
}

type DeleteLabsIdResponseObject interface {
	VisitDeleteLabsIdResponse(w http.ResponseWriter) error
}

type DeleteLabsId202JSONResponse LabInstance

func (response DeleteLabsId202JSONResponse) VisitDeleteLabsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type GetLabsIdRequestObject struct {
	Id LabId `json:"id"`
}

type GetLabsIdResponseObject interface {
	VisitGetLabsIdResponse(w http.ResponseWriter) error
}

type GetLabsId200JSONResponse LabInstanceDetail

func (response GetLabsId200JSONResponse) VisitGetLabsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLabsIdChecksRequestObject struct {
	Id LabId `json:"id"`
}

type GetLabsIdChecksResponseObject interface {
	VisitGetLabsIdChecksResponse(w http.ResponseWriter) error
}

type GetLabsIdChecks200JSONResponse []CheckRun

func (response GetLabsIdChecks200JSONResponse) VisitGetLabsIdChecksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostLabsIdChecksRequestObject struct {
	Id   LabId `json:"id"`
	Body *PostLabsIdChecksJSONRequestBody
}

type PostLabsIdChecksResponseObject interface {
	VisitPostLabsIdChecksResponse(w http.ResponseWriter) error
}

type PostLabsIdChecks202JSONResponse CheckRun

func (response PostLabsIdChecks202JSONResponse) VisitPostLabsIdChecksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type PostLabsIdExtendRequestObject struct {
	Id   LabId `json:"id"`
	Body *PostLabsIdExtendJSONRequestBody
}

type PostLabsIdExtendResponseObject interface {
	VisitPostLabsIdExtendResponse(w http.ResponseWriter) error
}

type PostLabsIdExtend200JSONResponse LabInstance

func (response PostLabsIdExtend200JSONResponse) VisitPostLabsIdExtendResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostLabsIdFreezeRequestObject struct {
	Id   LabId `json:"id"`
	Body *PostLabsIdFreezeJSONRequestBody
}

type PostLabsIdFreezeResponseObject interface {
	VisitPostLabsIdFreezeResponse(w http.ResponseWriter) error
}

type PostLabsIdFreeze200JSONResponse LabInstance

func (response PostLabsIdFreeze200JSONResponse) VisitPostLabsIdFreezeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLabsIdSshKeyRequestObject struct {
	Id LabId `json:"id"`
}

type GetLabsIdSshKeyResponseObject interface {
	VisitGetLabsIdSshKeyResponse(w http.ResponseWriter) error
}

type GetLabsIdSshKey200ApplicationxPemFileResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetLabsIdSshKey200ApplicationxPemFileResponse) VisitGetLabsIdSshKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/x-pem-file")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostLabsIdUnfreezeRequestObject struct {
	Id LabId `json:"id"`
}

type PostLabsIdUnfreezeResponseObject interface {
	VisitPostLabsIdUnfreezeResponse(w http.ResponseWriter) error
}

type PostLabsIdUnfreeze200JSONResponse LabInstance

func (response PostLabsIdUnfreeze200JSONResponse) VisitPostLabsIdUnfreezeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetReadyzRequestObject struct {
}

type GetReadyzResponseObject interface {
	VisitGetReadyzResponse(w http.ResponseWriter) error
}

type GetReadyz200Response struct {
}

func (response GetReadyz200Response) VisitGetReadyzResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetReadyz503Response struct {
}

func (response GetReadyz503Response) VisitGetReadyzResponse(w http.ResponseWriter) error {
	w.WriteHeader(503)
	return nil
}

type GetStreamLabsRequestObject struct {
}

type GetStreamLabsResponseObject interface {
	VisitGetStreamLabsResponse(w http.ResponseWriter) error
}

type GetStreamLabs200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetStreamLabs200TexteventStreamResponse) VisitGetStreamLabsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Аудит-лог
	// (GET /admin/audit)
	GetAdminAudit(ctx context.Context, request GetAdminAuditRequestObject) (GetAdminAuditResponseObject, error)
	// Состояние пула проектов
	// (GET /admin/projects)
	GetAdminProjects(ctx context.Context, request GetAdminProjectsRequestObject) (GetAdminProjectsResponseObject, error)
	// Quarantine проекта (заблокировать от аренды)
	// (POST /admin/projects/{id}/quarantine)
	PostAdminProjectsIdQuarantine(ctx context.Context, request PostAdminProjectsIdQuarantineRequestObject) (PostAdminProjectsIdQuarantineResponseObject, error)
	// Manual release (вернуть в FREE после ручного cleanup)
	// (POST /admin/projects/{id}/release)
	PostAdminProjectsIdRelease(ctx context.Context, request PostAdminProjectsIdReleaseRequestObject) (PostAdminProjectsIdReleaseResponseObject, error)
	// Текущая утилизация КИ
	// (GET /admin/quota)
	GetAdminQuota(ctx context.Context, request GetAdminQuotaRequestObject) (GetAdminQuotaResponseObject, error)
	// Текущие настройки
	// (GET /admin/settings)
	GetAdminSettings(ctx context.Context, request GetAdminSettingsRequestObject) (GetAdminSettingsResponseObject, error)
	// Обновить настройку (teacher/admin)
	// (PUT /admin/settings)
	PutAdminSettings(ctx context.Context, request PutAdminSettingsRequestObject) (PutAdminSettingsResponseObject, error)
	// Логин для teacher/admin (студенты — через LTI)
	// (POST /auth/login)
	PostAuthLogin(ctx context.Context, request PostAuthLoginRequestObject) (PostAuthLoginResponseObject, error)
	// Завершить сессию
	// (POST /auth/logout)
	PostAuthLogout(ctx context.Context, request PostAuthLogoutRequestObject) (PostAuthLogoutResponseObject, error)
	// Текущий пользователь
	// (GET /auth/me)
	GetAuthMe(ctx context.Context, request GetAuthMeRequestObject) (GetAuthMeResponseObject, error)
	// Детали запуска проверки (steps, stdout, summary)
	// (GET /checks/{id})
	GetChecksId(ctx context.Context, request GetChecksIdRequestObject) (GetChecksIdResponseObject, error)
	// Liveness probe
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// Список моих лаб (студент) или лаб курса (преподаватель)
	// (GET /labs)
	GetLabs(ctx context.Context, request GetLabsRequestObject) (GetLabsResponseObject, error)
	// Запросить новый стенд
	// (POST /labs)
	PostLabs(ctx context.Context, request PostLabsRequestObject) (PostLabsResponseObject, error)
	// Завершить стенд (cleanup)
	// (DELETE /labs/{id})
	DeleteLabsId(ctx context.Context, request DeleteLabsIdRequestObject) (DeleteLabsIdResponseObject, error)
	// Детали стенда
	// (GET /labs/{id})
	GetLabsId(ctx context.Context, request GetLabsIdRequestObject) (GetLabsIdResponseObject, error)
	// История проверок стенда
	// (GET /labs/{id}/checks)
	GetLabsIdChecks(ctx context.Context, request GetLabsIdChecksRequestObject) (GetLabsIdChecksResponseObject, error)
	// Запустить проверку
	// (POST /labs/{id}/checks)
	PostLabsIdChecks(ctx context.Context, request PostLabsIdChecksRequestObject) (PostLabsIdChecksResponseObject, error)
	// Продлить cleanup_at (только teacher)
	// (POST /labs/{id}/extend)
	PostLabsIdExtend(ctx context.Context, request PostLabsIdExtendRequestObject) (PostLabsIdExtendResponseObject, error)
	// Заморозить (студент — "сообщить о проблеме", teacher — manual freeze)
	// (POST /labs/{id}/freeze)
	PostLabsIdFreeze(ctx context.Context, request PostLabsIdFreezeRequestObject) (PostLabsIdFreezeResponseObject, error)
	// Скачать свой приватный SSH-ключ (только owner)
	// (GET /labs/{id}/ssh-key)
	GetLabsIdSshKey(ctx context.Context, request GetLabsIdSshKeyRequestObject) (GetLabsIdSshKeyResponseObject, error)
	// Снять заморозку (только teacher)
	// (POST /labs/{id}/unfreeze)
	PostLabsIdUnfreeze(ctx context.Context, request PostLabsIdUnfreezeRequestObject) (PostLabsIdUnfreezeResponseObject, error)
	// Readiness probe (DB + Redis)
	// (GET /readyz)
	GetReadyz(ctx context.Context, request GetReadyzRequestObject) (GetReadyzResponseObject, error)
	// SSE-стрим обновлений лаб текущего пользователя
	// (GET /stream/labs)
	GetStreamLabs(ctx context.Context, request GetStreamLabsRequestObject) (GetStreamLabsResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetAdminAudit operation middleware
func (sh *strictHandler) GetAdminAudit(w http.ResponseWriter, r *http.Request, params GetAdminAuditParams) {
	var request GetAdminAuditRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminAudit(ctx, request.(GetAdminAuditRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminAudit")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminAuditResponseObject); ok {
		if err := validResponse.VisitGetAdminAuditResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAdminProjects operation middleware
func (sh *strictHandler) GetAdminProjects(w http.ResponseWriter, r *http.Request, params GetAdminProjectsParams) {
	var request GetAdminProjectsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminProjects(ctx, request.(GetAdminProjectsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminProjects")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminProjectsResponseObject); ok {
		if err := validResponse.VisitGetAdminProjectsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAdminProjectsIdQuarantine operation middleware
func (sh *strictHandler) PostAdminProjectsIdQuarantine(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request PostAdminProjectsIdQuarantineRequestObject

	request.Id = id

	var body PostAdminProjectsIdQuarantineJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAdminProjectsIdQuarantine(ctx, request.(PostAdminProjectsIdQuarantineRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAdminProjectsIdQuarantine")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAdminProjectsIdQuarantineResponseObject); ok {
		if err := validResponse.VisitPostAdminProjectsIdQuarantineResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAdminProjectsIdRelease operation middleware
func (sh *strictHandler) PostAdminProjectsIdRelease(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request PostAdminProjectsIdReleaseRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAdminProjectsIdRelease(ctx, request.(PostAdminProjectsIdReleaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAdminProjectsIdRelease")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAdminProjectsIdReleaseResponseObject); ok {
		if err := validResponse.VisitPostAdminProjectsIdReleaseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAdminQuota operation middleware
func (sh *strictHandler) GetAdminQuota(w http.ResponseWriter, r *http.Request) {
	var request GetAdminQuotaRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminQuota(ctx, request.(GetAdminQuotaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminQuota")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminQuotaResponseObject); ok {
		if err := validResponse.VisitGetAdminQuotaResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAdminSettings operation middleware
func (sh *strictHandler) GetAdminSettings(w http.ResponseWriter, r *http.Request, params GetAdminSettingsParams) {
	var request GetAdminSettingsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminSettings(ctx, request.(GetAdminSettingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminSettings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminSettingsResponseObject); ok {
		if err := validResponse.VisitGetAdminSettingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutAdminSettings operation middleware
func (sh *strictHandler) PutAdminSettings(w http.ResponseWriter, r *http.Request) {
	var request PutAdminSettingsRequestObject

	var body PutAdminSettingsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutAdminSettings(ctx, request.(PutAdminSettingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutAdminSettings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutAdminSettingsResponseObject); ok {
		if err := validResponse.VisitPutAdminSettingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthLogin operation middleware
func (sh *strictHandler) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	var request PostAuthLoginRequestObject

	var body PostAuthLoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthLogin(ctx, request.(PostAuthLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthLoginResponseObject); ok {
		if err := validResponse.VisitPostAuthLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthLogout operation middleware
func (sh *strictHandler) PostAuthLogout(w http.ResponseWriter, r *http.Request) {
	var request PostAuthLogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthLogout(ctx, request.(PostAuthLogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthLogout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthLogoutResponseObject); ok {
		if err := validResponse.VisitPostAuthLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuthMe operation middleware
func (sh *strictHandler) GetAuthMe(w http.ResponseWriter, r *http.Request) {
	var request GetAuthMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthMe(ctx, request.(GetAuthMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAuthMeResponseObject); ok {
		if err := validResponse.VisitGetAuthMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetChecksId operation middleware
func (sh *strictHandler) GetChecksId(w http.ResponseWriter, r *http.Request, id CheckId) {
	var request GetChecksIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetChecksId(ctx, request.(GetChecksIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetChecksId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetChecksIdResponseObject); ok {
		if err := validResponse.VisitGetChecksIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLabs operation middleware
func (sh *strictHandler) GetLabs(w http.ResponseWriter, r *http.Request, params GetLabsParams) {
	var request GetLabsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLabs(ctx, request.(GetLabsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLabs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLabsResponseObject); ok {
		if err := validResponse.VisitGetLabsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostLabs operation middleware
func (sh *strictHandler) PostLabs(w http.ResponseWriter, r *http.Request) {
	var request PostLabsRequestObject

	var body PostLabsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostLabs(ctx, request.(PostLabsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostLabs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostLabsResponseObject); ok {
		if err := validResponse.VisitPostLabsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteLabsId operation middleware
func (sh *strictHandler) DeleteLabsId(w http.ResponseWriter, r *http.Request, id LabId) {
	var request DeleteLabsIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteLabsId(ctx, request.(DeleteLabsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteLabsId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteLabsIdResponseObject); ok {
		if err := validResponse.VisitDeleteLabsIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLabsId operation middleware
func (sh *strictHandler) GetLabsId(w http.ResponseWriter, r *http.Request, id LabId) {
	var request GetLabsIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLabsId(ctx, request.(GetLabsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLabsId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLabsIdResponseObject); ok {
		if err := validResponse.VisitGetLabsIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLabsIdChecks operation middleware
func (sh *strictHandler) GetLabsIdChecks(w http.ResponseWriter, r *http.Request, id LabId) {
	var request GetLabsIdChecksRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLabsIdChecks(ctx, request.(GetLabsIdChecksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLabsIdChecks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLabsIdChecksResponseObject); ok {
		if err := validResponse.VisitGetLabsIdChecksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostLabsIdChecks operation middleware
func (sh *strictHandler) PostLabsIdChecks(w http.ResponseWriter, r *http.Request, id LabId) {
	var request PostLabsIdChecksRequestObject

	request.Id = id

	var body PostLabsIdChecksJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostLabsIdChecks(ctx, request.(PostLabsIdChecksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostLabsIdChecks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostLabsIdChecksResponseObject); ok {
		if err := validResponse.VisitPostLabsIdChecksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostLabsIdExtend operation middleware
func (sh *strictHandler) PostLabsIdExtend(w http.ResponseWriter, r *http.Request, id LabId) {
	var request PostLabsIdExtendRequestObject

	request.Id = id

	var body PostLabsIdExtendJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostLabsIdExtend(ctx, request.(PostLabsIdExtendRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostLabsIdExtend")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostLabsIdExtendResponseObject); ok {
		if err := validResponse.VisitPostLabsIdExtendResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostLabsIdFreeze operation middleware
func (sh *strictHandler) PostLabsIdFreeze(w http.ResponseWriter, r *http.Request, id LabId) {
	var request PostLabsIdFreezeRequestObject

	request.Id = id

	var body PostLabsIdFreezeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostLabsIdFreeze(ctx, request.(PostLabsIdFreezeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostLabsIdFreeze")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostLabsIdFreezeResponseObject); ok {
		if err := validResponse.VisitPostLabsIdFreezeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLabsIdSshKey operation middleware
func (sh *strictHandler) GetLabsIdSshKey(w http.ResponseWriter, r *http.Request, id LabId) {
	var request GetLabsIdSshKeyRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLabsIdSshKey(ctx, request.(GetLabsIdSshKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLabsIdSshKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLabsIdSshKeyResponseObject); ok {
		if err := validResponse.VisitGetLabsIdSshKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostLabsIdUnfreeze operation middleware
func (sh *strictHandler) PostLabsIdUnfreeze(w http.ResponseWriter, r *http.Request, id LabId) {
	var request PostLabsIdUnfreezeRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostLabsIdUnfreeze(ctx, request.(PostLabsIdUnfreezeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostLabsIdUnfreeze")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostLabsIdUnfreezeResponseObject); ok {
		if err := validResponse.VisitPostLabsIdUnfreezeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadyz operation middleware
func (sh *strictHandler) GetReadyz(w http.ResponseWriter, r *http.Request) {
	var request GetReadyzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadyz(ctx, request.(GetReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadyz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadyzResponseObject); ok {
		if err := validResponse.VisitGetReadyzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetStreamLabs operation middleware
func (sh *strictHandler) GetStreamLabs(w http.ResponseWriter, r *http.Request) {
	var request GetStreamLabsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStreamLabs(ctx, request.(GetStreamLabsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStreamLabs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStreamLabsResponseObject); ok {
		if err := validResponse.VisitGetStreamLabsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RcbW/bRp7/KgPevXBa2XLatNvqXZo4rW/dbWoluANiQxmTY2tqashwho6VQIAfetct",
	"kmtuFwt00cXeoXtfQHHjjWLHyleY+Qr3SQ7znyFFipQsKXZ291Usch7/D7//I/PYcYNWGDDCBHdqj50Q",
	"R7hFBIng140mcbeXPf0nZU7NCbFoOhWH4RZxag71nIoTkQcxjYjn1EQUk4rD3SZpYT1jM4haWDg1J45h",
	"pGiHehYXEWVbTqdTcVbwxmUt3tGTeRgwTsxNArbpU1fov92ACcLgTxyGPnWxoAGrhlGw4ZPW+9/wgOl3",
	"g83+OSKbTs35p+qAVlXzlldvm1lmS49wN6KhXs6pOfIn2Zdn6lt5KnvyRB2guQdxIDCqojAIfERaoWij",
	"KuICC4Ja2G1SRtAODXw4zxWnU3FuBdEG9TzC3um5f5Rd+UbtyWP1vTyWZ7Kvj/KbQNwKYua905P8WR4j",
	"eSa78pV8MTjKXYZj0Qwi+oj8DY7TlUfqQPbVnuzJl7Ivj2RXnoE82yX0Dtdjj4qlHXuqMApCEglqZBG7",
	"IogaMSdRg3plwsxi38cbPknEfki4K075tMKwbWrYVXgRuG4cRcRrYJFbyMOCzAvaImWrhbjtB1gv2DGa",
	"SbiwFzj3wDze+Ia4Ytb7JtPNi8clUGKfBDBOTwHoWo1ZkfyuftMQpBX6WJDGhLTcpIzy5niSXRTffLzR",
	"oIwLzNyJz8cFjsRbHg+QSE8nLG45tXvOg5jEBIA4ZkwP0lLAOTzaxNSHP/TqQSycikOiKNBovV7KwlYL",
	"R+0JpGUcN28SgakPSuT7X206tXvjlTmVgk6loIWM0w2fNLjw9OnL1IQLEsJYKkiLlypyjH2jEGQ3JK4g",
	"Vj1ahHO8RUasikXMs2QOtp2K4zYx28pTNmYRwW4TaFVx+DYNwxHUFZhvN4zlnEg77AMcRbhdNmLdWOeb",
	"JPSDdl2QsOTyQqtQlnCUCbJFogvTFh9z0QCZmgxjLkgD8rwJCfOM5FPWCKNgKyKca27ErkuIl2eYlkDC",
	"OBajlECQMGVTsgP2/cDVSBRGAVC/4rgR0Q+2STvENNJaFwU7lNOANRgRD4NIC8xGEIjGTsupOA8xFQ3O",
	"m3BIKij2GwByJWcoEwbthlm0KUFLn2AWh29FVTeIIz4xkpnLT2ebpgDWaYHfcmVm05Vg6jiYWsEbdRiX",
	"TGhEBFuvZYIdYo8wMc6hKMyJ2WZEyCPyVmyNQ29KRnWyLv094+MPHz8rLkWOJQTNicn6eKGe1mhk9aFo",
	"NzzAxEbRNpyzZAZLCwCsXbVGRHgQRy4pMTSbfoAFZVsNOrRn0RAMrWvhwspFUXZItANkn2rZMhDRDOLC",
	"4E4jMn7XZJZ5pPWpD7sjFosbEEZpVLS/B8BpmGPwOiLYa4NhJe62ebQZBY8IyyG2hjfz0gsYgWnfGENe",
	"BuBJcABykA0NVm/dQL/6ZPFXyAYdyAOh4wa7s3gaeKQ4vS60piEwdkgPqSCysLWAllZXG1/f/erO9cbS",
	"v91YWrq5dLNMm71UwIvAmAH2MdauaMEFFT4ZIwtZkInouaoOb5NV053LFPe2ZWbR4bB20muIoAEu8myI",
	"nFg0LQNxREbcf+IQq+EFLUzZKA3bpo28BSl3cwzqGx9wKss3wumb0PBYYlvj0xnNjoIuavvhVAZMyevS",
	"gxhHmAkKGuURN2i1KNf+ywi9+lprdJ3hkDeDEtZ7lG+fd5VVC5/gfhLhNqd0ISLcmmYL0YwIbwa+1wiN",
	"sHpkE8e+cGqfLqars7i1YcQpFtSnjyAvkUwov2JhZgvvFvGihXdRsImw7yN9EFJBMSce2gwilB4MGR+w",
	"5DD2qoXnO26Yg4PkTZlcpGMnI1jZEunbAjFEILBfesSY0fJYTd9/wqPXidDGtLjtNmmXq5IbhDnh3/KD",
	"DeyDBYoaxl2xP7L+SnkIoNeaFbqm97gGczbaU3mIO9iP9Z3HUfAuLP0PSMfs5bJWSh88eZsct8xG3eUk",
	"+rIsWIIrjEsZTEj9kageBT5pUJYQK0NLn+CIER0sCoLdJokmjP6GPUaP8tDH7cbII5DWSGdjssvpO2RP",
	"biOAzMkrDvZalJXfoBBB5E5sly9yDbxdN46oaNc1PBl+cAJm6UYQbFOSliJc8zMtRrj+VsOOHFwIh/TX",
	"pG3yxJRtBiVO4VL9Drp+exmp38pT9YN8KbsIEscn8ljtqwO1J7vqP2RP9pDsy+fyVHbVd/JMPVH/jvQP",
	"+RxGd2262bzQEyEV/kL25RFkx5H8Sf4RzX0VElYX2N2+srDG1th778n/UodmsDqQPfWt7MkTs6N69t57",
	"NfSFEOFXzG8jc190P3PP+2juX/71Dvqi/sFHH1eQPFJP5AvZVb9TB2pfPUPyjeyrfXkqj9fYyp1l5OOY",
	"uU0ke/JU9lAVx6JZ9YMtytKzmGII3FmeqAO9v/pPdSC7SO3LN/IYjpU7Ivq/vT8g2YML9zVh9MvkQU+T",
	"YwF9HqAmZp5PIo5kD92pz8sTqLfApdeY+lbtmY0tzbpI/gJ/Hqs92VN76lD9kNypJ18iePO7hTWWeqs1",
	"54YfxB5awRvocyzIQ9zWTNVAQSJuOL24cHVhETLrIWE4pE7N+RAeVaCsBaJWBZmu4tgzJmyLwD8aHcAv",
	"WPacmvM5Edf1MKgfwOxBPe6elc4HMYnaA+GELH+2NlZQmfJ5+TLEVJW78gU51YFG6UJjcwLlq/m0BRQY",
	"rJZ6WFcXF8Evoi0NIB/BL8rMr6uVgjPfWR8qBn6wuDimbFQsF00U4mcqPsWAuVBKCrYNIiVZcUfrqnwh",
	"e+pgXp7KvvxFUwpvccgQgjCs6wlWiGxIwc+Vo9vJwAlFKRPNzCBSSW5m4kpbNvh4J1xKosuZWPSzxjwA",
	"o2cARsdIvlGHGqkR1Ev78lhDm8blLPc0H+bDIPBLWVh9TL1ONRMwDVXh711GeXy94oQBL5Gb2wHPC86y",
	"93U2lrN1v88Crz0Vc/Je0CC72aJshbAt0XRqH51n7O2sEtPeGaZFp1yWzmHw4KZ5fnbRnLbdYKH78kSb",
	"DVP3VQfqqbboB0h21Z6xMOrJlWmZHxGfYP73x/lVe66ZiPklZjH2kb0bmpNHYHLPtEuiqXaEbq0uLWUc",
	"CQTGWJv5vvxF9pHN00xATZMPPA8Kv7ZZw7cCmXHYkk9iTIQofwEJO1Tfy656hsBbAw9Ki5t1grRvVyCB",
	"uXGWBtyEZOdbhHoycCKLYGKgrIC9dew20ngkEd2U4nz5RiNJGMxkNAYs7tlmFuv69+UrjSUF3qacXO9U",
	"nDAuU9W4wMpZcXmCa9sof3KUvcjNJ6Pxf8vnABtH2n/S4DJEZXWI5mxsadTlyjiqg1KlAQyg8mjEjEVz",
	"BYZdlG1Mw+tU9M2T0o4czh8GkTdkSD85z5AmC6bzZzOp10rqGETMm1gaZWPmTsW5tnh1FMvTZau5xq5s",
	"xO7U7q3nOP4nMBI9eYbkC3mqnqEce9EccP/QNI2pA/UEYkn1HZigY/kSrdxZzslALJpDnLdNIeey3rS+",
	"nE+aotT+KLvGKKrfWrlV+5AY2Jc99cOY05nEzEiUj0XzS3KZhs6mv0ao5sy8LsfMV+AiyFP1NOm2g1j+",
	"VD0tpxBkvY1jNY5KUH/ky95l0mmoa2kiKPuDPNYeJ6RRwOl8ow7VvjwZxBjGjzqRPTQHRegKMi1MFWSX",
	"yQq2oYYxJXlrX3bwwZBq0voLxdhqk2BfNB+NI+gXdsg0zuII7V6hO4QRzqGYSjK3McewjPbxxlhvZ0W/",
	"n8jJyTYcTJUFIbuhD/Vc44VPFhJP2jCQdoQMZ2i5aENaSh/QeTceUL4lYqbQ+Y3sqX0dPiH5WvZlL81x",
	"DoP1lSSLaF8DEuypfQjDoC0ZAOEFoGcKBlmhB8kAkbfgPdTG+3N2O3Ocv2q10xu/1n9oKD6woHMi+wi2",
	"A2MDuUvZk0fyTD2RrzLZWJuJtYddWGPy97IvX9rV9ehjCBW1KsuX6kltjc2ja4ufIggblnZNN1kNuX7M",
	"BYlQpmKI1uLFxQ9JWtlLZv4muBURYuO1mk1GFFIRJmNqTN8b2ZVnyfQVvHHdhy6J666gO6SG1KEmBLLZ",
	"6ae560KEYrPSXXNZyN9C9GtvDVnToqW0mngx/tF0zWTTd3wN+UrjmpFmc5uuXph9yWllSbv6zyCAWlFs",
	"4/y1xU/PN8zppxIl7gqIFvgn1s3uQ2UgqwdFPUzAOrXJHvGJqRvmZeUmPNfSUmaXP3hXdLthEg82NQHW",
	"+Eie6tshrU391I18oZ5O4tOlCDFXktJIsWqcGbtcN6XYKje1p5IpSnVLgXgq38N8F2Q8j1RwrGN3nsVf",
	"9oxn57wLs5hpL5/BJv7RJpP3TJ4n691pMzmCpjN7dAlVxyUACxS8EMSe4YOLYRQuLDEb9n5w4b59KfD+",
	"PocSslcOpYemkGmgNOfbq8MyhufVgewKYj7vuSwxWDI7XFhiA5ZrbLQbnLgBMy2naRXvk4+v5ep4Hy+W",
	"FPKG0hiFBd+iNPAuDEsRAv4HuP5CYyiIwaDbHs3lPFCb3rhyjnWtmrbuy5SKW2aHi5IK24e+GURZsRjS",
	"p78UKbGAbppysO0SkC9Rkg5dcColDZ2ZmhPeTVJlVxet0L3DItTfRtI05LwGY6N9QiNtQ4EXUHLNgSit",
	"L5+r7xNs6ifw9BzcoNfyeM2pJIyAWS1T7DHMPFdIOW/O2x6x8aa8zpu/hpasKei4Ox+S1vwmNT1Go0vY",
	"BZrdXvpyXn0LJHqt48piCHsC/TndJFV3JPuQnYIvQU0oaoLCev0LaENRP6jvhvQ4eMhKtfhiXKTks47L",
	"1P+7yR5/T9L9szxTz4ywvswJOqT+p0BSCIfH5rlWzYhJ01wV56PFD4uvPBIS5hHmUsJRzPAOpqZlcVxe",
	"TG9NB4kxNHfzM/Q+WiUe5VdGZcm4iAhuDSfLhrP20Q6J5uuECQQdLHwByZ9kV/4Ver6eobSWciK7oO/3",
	"PSxwDT3WbO2srbG1NXZ/wcxFWtF4bY3d9/HGQrav3btfQfDQfkKTfE2nH4OTUxwNdc4Fbmuq9xdKEgyf",
	"E1GHO6ZZhrFCKciuqBJ90HlDmilRol5fQnZiXgbr9aV5S6eefG0a+kxNCkJHk8k2GS3w601++xhK3SMy",
	"3M8yTLV7rneGBKTQwnhvXWux+bDHqH7+Ap+RJmUeYluU7c6HUbCr8TWOfKfmVHFIqztXAQbsvgVTPKal",
	"MNNaFosmfDqVn7xyZxldXfgQEeaFAWWCozn5HMoxdmdk/9sBWFbty+6VTD+YoCVLyj+VtUnK40z0pJ4U",
	"DN37aHwiMdlSS1TJnj8O0vJI9lCaFdGwc6D20HXzafH8cEiXyTgbn75k7f+FSd2M2KRdRn0tVsPJvbm0",
	"npnQftAjUbL8n4fLzwhi+Fdg8g6TNQu10tzaaam07PgjOhhGndM0MpQsNNwOV7IAdMUVpxbRLKkR+nSH",
	"zJuMjhYHcHSOsql6o9aFFU1pY95NwmI73uJsZ73z/wEAAP//jHGz9UZFAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
