/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (DB + Redis) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description dependencies unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Логин для teacher/admin (студенты — через LTI) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Set-Cookie clg_session */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Завершить сессию */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий пользователь */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserMe"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список моих лаб (студент) или лаб курса (преподаватель) */
        get: {
            parameters: {
                query?: {
                    course_id?: string;
                    state?: components["schemas"]["LabState"][];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LabInstance"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Запросить новый стенд
         * @description Студент может иметь только один активный стенд на курс.
         *     Возможные отказы:
         *     - 409 QuotaExceeded: cluster utilization >threshold
         *     - 409 NoFreeProject: пул проектов исчерпан
         *     - 409 LabAlreadyActive: уже есть активная лаба на этот курс
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        course_id: string;
                        /** Format: uuid */
                        lab_template_id: string;
                    };
                };
            };
            responses: {
                /** @description Создано */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LabInstance"];
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LabId"];
            };
            cookie?: never;
        };
        /** Детали стенда */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["LabId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LabInstanceDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Завершить стенд (cleanup) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["LabId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cleanup поставлен в очередь */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LabInstance"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labs/{id}/freeze": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LabId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Заморозить (студент — "сообщить о проблеме", teacher — manual freeze) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["LabId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reason: string;
                        /** @description Только teacher. Default — из Settings. */
                        freeze_for_seconds?: number;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LabInstance"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labs/{id}/unfreeze": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LabId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Снять заморозку (только teacher) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["LabId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LabInstance"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labs/{id}/extend": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LabId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Продлить cleanup_at (только teacher) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["LabId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        extend_by_seconds: number;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LabInstance"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labs/{id}/ssh-key": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LabId"];
            };
            cookie?: never;
        };
        /** Скачать свой приватный SSH-ключ (только owner) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["LabId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PEM-формат */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/x-pem-file": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labs/{id}/checks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LabId"];
            };
            cookie?: never;
        };
        /** История проверок стенда */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["LabId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckRun"][];
                    };
                };
            };
        };
        put?: never;
        /** Запустить проверку */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["LabId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        check_template_id: string;
                    };
                };
            };
            responses: {
                /** @description В очереди */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckRun"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CheckId"];
            };
            cookie?: never;
        };
        /** Детали запуска проверки (steps, stdout, summary) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["CheckId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckRunDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Состояние пула проектов */
        get: {
            parameters: {
                query?: {
                    ki_domain_id?: string;
                    state?: components["schemas"]["ProjectState"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/projects/{id}/quarantine": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quarantine проекта (заблокировать от аренды) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reason: string;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/projects/{id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manual release (вернуть в FREE после ручного cleanup) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущие настройки */
        get: {
            parameters: {
                query?: {
                    scope?: "global" | "per_course" | "per_lab_template";
                    scope_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Setting"][];
                    };
                };
            };
        };
        /** Обновить настройку (teacher/admin) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SettingUpdate"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Setting"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущая утилизация КИ */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuotaSnapshot"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Аудит-лог */
        get: {
            parameters: {
                query?: {
                    kind?: string;
                    actor_user_id?: string;
                    since?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditEvent"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream/labs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SSE-стрим обновлений лаб текущего пользователя
         * @description Server-Sent Events. Каждая строка — `data: {json}\n\n`. Event types:
         *     `lab.state_changed`, `lab.deploy_progress`, `check.state_changed`, `quota.snapshot`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 problem details */
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** @description Stable error code, e.g. ERR_QUOTA_EXCEEDED */
            code?: string;
        };
        UserMe: {
            /** Format: uuid */
            id: string;
            display_name: string;
            email?: string;
            /** @enum {string} */
            role: "student" | "teacher" | "admin";
            courses?: {
                /** Format: uuid */
                id?: string;
                name?: string;
                /** @enum {string} */
                role_in_course?: "learner" | "teacher";
            }[];
        };
        /** @enum {string} */
        LabState: "pending_quota" | "pending_project" | "deploying" | "ready" | "checking" | "frozen" | "failed" | "cleaning" | "done" | "rejected";
        LabInstance: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            student_user_id: string;
            /** Format: uuid */
            course_id: string;
            /** Format: uuid */
            lab_template_id: string;
            /** Format: uuid */
            project_id?: string | null;
            state: components["schemas"]["LabState"];
            state_reason?: string | null;
            /** Format: date-time */
            cleanup_at?: string | null;
            /** Format: date-time */
            unfreeze_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        LabInstanceDetail: components["schemas"]["LabInstance"] & {
            ki_resources?: {
                server_ids?: string[];
                floating_ips?: string[];
                network_id?: string;
            };
            deploy_steps?: components["schemas"]["LabDeployStep"][];
            latest_check_run?: components["schemas"]["CheckRun"];
        };
        LabDeployStep: {
            /** @enum {string} */
            step_name?: "allocate_project" | "create_keypair" | "provision_network" | "boot_vm" | "wait_ssh" | "initial_check";
            /** @enum {string} */
            status?: "pending" | "in_progress" | "succeeded" | "failed" | "compensated";
            attempt?: number;
            last_error?: string | null;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
        };
        CheckRun: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            lab_instance_id?: string;
            /** Format: uuid */
            check_template_id?: string;
            /** @enum {string} */
            state?: "queued" | "running" | "passed" | "failed" | "timeout" | "errored";
            summary?: string | null;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
        };
        CheckRunDetail: components["schemas"]["CheckRun"] & {
            steps?: {
                task_name?: string;
                /** @enum {string} */
                status?: "ok" | "changed" | "failed" | "unreachable" | "skipped";
                expected?: unknown;
                actual?: unknown;
                message?: string;
            }[];
            ansible_stdout?: string;
        };
        /** @enum {string} */
        ProjectState: "free" | "allocated" | "cleaning" | "quarantine" | "decommissioned";
        Project: {
            /** Format: uuid */
            id?: string;
            ki_project_id?: string;
            ki_domain_id?: string;
            name?: string;
            state?: components["schemas"]["ProjectState"];
            /** Format: uuid */
            allocated_to_lab_id?: string | null;
            cleanup_failures?: number;
            /** Format: date-time */
            last_state_change_at?: string;
        };
        QuotaSnapshot: {
            vcpus?: components["schemas"]["Resource"];
            ram?: components["schemas"]["Resource"];
            disk?: components["schemas"]["Resource"];
            utilization_pct?: {
                vcpus?: number;
                ram?: number;
                disk?: number;
                /** @description max of all three, used for threshold check */
                max?: number;
            };
            /** Format: date-time */
            fetched_at?: string;
            /** @default 90 */
            threshold_pct: number;
        };
        Resource: {
            used?: number;
            total?: number;
            unit?: string;
        };
        Setting: {
            key?: string;
            value?: unknown;
            /** @enum {string} */
            scope?: "global" | "per_course" | "per_lab_template";
            /** Format: uuid */
            scope_id?: string | null;
            /** Format: uuid */
            updated_by_user_id?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        SettingUpdate: {
            key: string;
            value: unknown;
            /** @enum {string} */
            scope: "global" | "per_course" | "per_lab_template";
            /** Format: uuid */
            scope_id?: string | null;
        };
        AuditEvent: {
            /** Format: uuid */
            id?: string;
            kind?: string;
            /** Format: uuid */
            actor_user_id?: string | null;
            subject_type?: string;
            /** Format: uuid */
            subject_id?: string | null;
            payload?: unknown;
            request_id?: string | null;
            /** Format: date-time */
            occurred_at?: string;
        };
    };
    responses: {
        /** @description Не авторизован */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Запрещено */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Не найдено */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Конфликт (quota / pool empty / state machine violation) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        LabId: string;
        CheckId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
