// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: audit.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const queryAuditEvents = `-- name: QueryAuditEvents :many
SELECT id, kind, actor_user_id, subject_type, subject_id, payload, request_id, occurred_at
FROM audit_events
WHERE ($1::text IS NULL OR kind = $1::text)
  AND ($2::uuid IS NULL OR actor_user_id = $2::uuid)
  AND ($3::timestamptz IS NULL OR occurred_at >= $3::timestamptz)
ORDER BY occurred_at DESC, id DESC
LIMIT $4
`

type QueryAuditEventsParams struct {
	Kind        *string            `json:"kind"`
	ActorUserID uuid.NullUUID      `json:"actor_user_id"`
	Since       pgtype.Timestamptz `json:"since"`
	Limit       int32              `json:"limit"`
}

func (q *Queries) QueryAuditEvents(ctx context.Context, arg QueryAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, queryAuditEvents,
		arg.Kind,
		arg.ActorUserID,
		arg.Since,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ActorUserID,
			&i.SubjectType,
			&i.SubjectID,
			&i.Payload,
			&i.RequestID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
