// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: check_run.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCheckRun = `-- name: CreateCheckRun :exec
INSERT INTO check_runs (
    id,
    lab_instance_id,
    check_template_id,
    triggered_by_user_id,
    state,
    summary,
    ansible_stdout,
    started_at,
    finished_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
`

type CreateCheckRunParams struct {
	ID                uuid.UUID          `json:"id"`
	LabInstanceID     uuid.UUID          `json:"lab_instance_id"`
	CheckTemplateID   uuid.UUID          `json:"check_template_id"`
	TriggeredByUserID uuid.NullUUID      `json:"triggered_by_user_id"`
	State             string             `json:"state"`
	Summary           string             `json:"summary"`
	AnsibleStdout     string             `json:"ansible_stdout"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) CreateCheckRun(ctx context.Context, arg CreateCheckRunParams) error {
	_, err := q.db.Exec(ctx, createCheckRun,
		arg.ID,
		arg.LabInstanceID,
		arg.CheckTemplateID,
		arg.TriggeredByUserID,
		arg.State,
		arg.Summary,
		arg.AnsibleStdout,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}

const deleteCheckRunSteps = `-- name: DeleteCheckRunSteps :exec
DELETE FROM check_run_steps
WHERE check_run_id = $1
`

func (q *Queries) DeleteCheckRunSteps(ctx context.Context, checkRunID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCheckRunSteps, checkRunID)
	return err
}

const getCheckRunByID = `-- name: GetCheckRunByID :one
SELECT id, lab_instance_id, check_template_id, triggered_by_user_id, state, summary, ansible_stdout, ansible_stats, started_at, finished_at, created_at
FROM check_runs
WHERE id = $1
`

func (q *Queries) GetCheckRunByID(ctx context.Context, id uuid.UUID) (CheckRun, error) {
	row := q.db.QueryRow(ctx, getCheckRunByID, id)
	var i CheckRun
	err := row.Scan(
		&i.ID,
		&i.LabInstanceID,
		&i.CheckTemplateID,
		&i.TriggeredByUserID,
		&i.State,
		&i.Summary,
		&i.AnsibleStdout,
		&i.AnsibleStats,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCheckTemplateByID = `-- name: GetCheckTemplateByID :one
SELECT id, slug, name, lab_template_id, playbook_path, timeout_seconds, expected_outcome, created_at
FROM check_templates
WHERE id = $1
`

func (q *Queries) GetCheckTemplateByID(ctx context.Context, id uuid.UUID) (CheckTemplate, error) {
	row := q.db.QueryRow(ctx, getCheckTemplateByID, id)
	var i CheckTemplate
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.LabTemplateID,
		&i.PlaybookPath,
		&i.TimeoutSeconds,
		&i.ExpectedOutcome,
		&i.CreatedAt,
	)
	return i, err
}

const insertCheckRunStep = `-- name: InsertCheckRunStep :exec
INSERT INTO check_run_steps (
    check_run_id,
    seq,
    task_name,
    status,
    expected,
    actual,
    message
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    NULLIF($7, '')
)
`

type InsertCheckRunStepParams struct {
	CheckRunID uuid.UUID   `json:"check_run_id"`
	Seq        int32       `json:"seq"`
	TaskName   string      `json:"task_name"`
	Status     string      `json:"status"`
	Expected   []byte      `json:"expected"`
	Actual     []byte      `json:"actual"`
	Message    interface{} `json:"message"`
}

func (q *Queries) InsertCheckRunStep(ctx context.Context, arg InsertCheckRunStepParams) error {
	_, err := q.db.Exec(ctx, insertCheckRunStep,
		arg.CheckRunID,
		arg.Seq,
		arg.TaskName,
		arg.Status,
		arg.Expected,
		arg.Actual,
		arg.Message,
	)
	return err
}

const listCheckRunSteps = `-- name: ListCheckRunSteps :many
SELECT id, check_run_id, seq, task_name, status, expected, actual, message
FROM check_run_steps
WHERE check_run_id = $1
ORDER BY seq ASC
`

func (q *Queries) ListCheckRunSteps(ctx context.Context, checkRunID uuid.UUID) ([]CheckRunStep, error) {
	rows, err := q.db.Query(ctx, listCheckRunSteps, checkRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckRunStep{}
	for rows.Next() {
		var i CheckRunStep
		if err := rows.Scan(
			&i.ID,
			&i.CheckRunID,
			&i.Seq,
			&i.TaskName,
			&i.Status,
			&i.Expected,
			&i.Actual,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckRunsByLab = `-- name: ListCheckRunsByLab :many
SELECT id, lab_instance_id, check_template_id, triggered_by_user_id, state, summary, ansible_stdout, ansible_stats, started_at, finished_at, created_at
FROM check_runs
WHERE lab_instance_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListCheckRunsByLabParams struct {
	LabInstanceID uuid.UUID `json:"lab_instance_id"`
	Limit         int32     `json:"limit"`
}

func (q *Queries) ListCheckRunsByLab(ctx context.Context, arg ListCheckRunsByLabParams) ([]CheckRun, error) {
	rows, err := q.db.Query(ctx, listCheckRunsByLab, arg.LabInstanceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckRun{}
	for rows.Next() {
		var i CheckRun
		if err := rows.Scan(
			&i.ID,
			&i.LabInstanceID,
			&i.CheckTemplateID,
			&i.TriggeredByUserID,
			&i.State,
			&i.Summary,
			&i.AnsibleStdout,
			&i.AnsibleStats,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCheckRun = `-- name: UpdateCheckRun :exec
UPDATE check_runs
SET state = $1,
    summary = $2,
    ansible_stdout = $3,
    started_at = $4,
    finished_at = $5
WHERE id = $6
`

type UpdateCheckRunParams struct {
	State         string             `json:"state"`
	Summary       string             `json:"summary"`
	AnsibleStdout string             `json:"ansible_stdout"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	ID            uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateCheckRun(ctx context.Context, arg UpdateCheckRunParams) error {
	_, err := q.db.Exec(ctx, updateCheckRun,
		arg.State,
		arg.Summary,
		arg.AnsibleStdout,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}
