// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: course.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const enrollCourseUser = `-- name: EnrollCourseUser :exec
INSERT INTO enrollments (
    user_id,
    course_id,
    role_in_course,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    COALESCE($4, now())
)
ON CONFLICT (user_id, course_id) DO UPDATE
SET role_in_course = EXCLUDED.role_in_course
`

type EnrollCourseUserParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	CourseID     uuid.UUID   `json:"course_id"`
	RoleInCourse string      `json:"role_in_course"`
	CreatedAt    interface{} `json:"created_at"`
}

func (q *Queries) EnrollCourseUser(ctx context.Context, arg EnrollCourseUserParams) error {
	_, err := q.db.Exec(ctx, enrollCourseUser,
		arg.UserID,
		arg.CourseID,
		arg.RoleInCourse,
		arg.CreatedAt,
	)
	return err
}

const getCourseByExternalID = `-- name: GetCourseByExternalID :one
SELECT id, external_id, name, ki_domain_id, created_at
FROM courses
WHERE external_id = $1
`

func (q *Queries) GetCourseByExternalID(ctx context.Context, externalID string) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByExternalID, externalID)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.KiDomainID,
		&i.CreatedAt,
	)
	return i, err
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT id, external_id, name, ki_domain_id, created_at
FROM courses
WHERE id = $1
`

func (q *Queries) GetCourseByID(ctx context.Context, id uuid.UUID) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByID, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.KiDomainID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCourse = `-- name: UpsertCourse :one
INSERT INTO courses (
    id,
    external_id,
    name,
    ki_domain_id,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    COALESCE($5, now())
)
ON CONFLICT (external_id) DO UPDATE
SET name = EXCLUDED.name,
    ki_domain_id = EXCLUDED.ki_domain_id
RETURNING id
`

type UpsertCourseParams struct {
	ID         uuid.UUID   `json:"id"`
	ExternalID string      `json:"external_id"`
	Name       string      `json:"name"`
	KiDomainID string      `json:"ki_domain_id"`
	CreatedAt  interface{} `json:"created_at"`
}

func (q *Queries) UpsertCourse(ctx context.Context, arg UpsertCourseParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertCourse,
		arg.ID,
		arg.ExternalID,
		arg.Name,
		arg.KiDomainID,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
