// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deploy_step.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDeployStep = `-- name: GetDeployStep :one
SELECT id, lab_instance_id, step_name, status, attempt, last_error, result, started_at, finished_at
FROM lab_deploy_steps
WHERE lab_instance_id = $1
  AND step_name = $2
`

type GetDeployStepParams struct {
	LabInstanceID uuid.UUID `json:"lab_instance_id"`
	StepName      string    `json:"step_name"`
}

func (q *Queries) GetDeployStep(ctx context.Context, arg GetDeployStepParams) (LabDeployStep, error) {
	row := q.db.QueryRow(ctx, getDeployStep, arg.LabInstanceID, arg.StepName)
	var i LabDeployStep
	err := row.Scan(
		&i.ID,
		&i.LabInstanceID,
		&i.StepName,
		&i.Status,
		&i.Attempt,
		&i.LastError,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listDeployStepsByLab = `-- name: ListDeployStepsByLab :many
SELECT id, lab_instance_id, step_name, status, attempt, last_error, result, started_at, finished_at
FROM lab_deploy_steps
WHERE lab_instance_id = $1
ORDER BY started_at ASC NULLS LAST, step_name
`

func (q *Queries) ListDeployStepsByLab(ctx context.Context, labInstanceID uuid.UUID) ([]LabDeployStep, error) {
	rows, err := q.db.Query(ctx, listDeployStepsByLab, labInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LabDeployStep{}
	for rows.Next() {
		var i LabDeployStep
		if err := rows.Scan(
			&i.ID,
			&i.LabInstanceID,
			&i.StepName,
			&i.Status,
			&i.Attempt,
			&i.LastError,
			&i.Result,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeployStep = `-- name: UpsertDeployStep :exec
INSERT INTO lab_deploy_steps (
    lab_instance_id,
    step_name,
    status,
    attempt,
    last_error,
    result,
    started_at,
    finished_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    NULLIF($5, ''),
    $6,
    $7,
    $8
)
ON CONFLICT (lab_instance_id, step_name) DO UPDATE
SET status = EXCLUDED.status,
    attempt = EXCLUDED.attempt,
    last_error = EXCLUDED.last_error,
    result = EXCLUDED.result,
    started_at = EXCLUDED.started_at,
    finished_at = EXCLUDED.finished_at
`

type UpsertDeployStepParams struct {
	LabInstanceID uuid.UUID          `json:"lab_instance_id"`
	StepName      string             `json:"step_name"`
	Status        string             `json:"status"`
	Attempt       int32              `json:"attempt"`
	Column5       interface{}        `json:"column_5"`
	Result        []byte             `json:"result"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) UpsertDeployStep(ctx context.Context, arg UpsertDeployStepParams) error {
	_, err := q.db.Exec(ctx, upsertDeployStep,
		arg.LabInstanceID,
		arg.StepName,
		arg.Status,
		arg.Attempt,
		arg.Column5,
		arg.Result,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}
