// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: lab.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLabInstance = `-- name: CreateLabInstance :exec
INSERT INTO lab_instances (
    id,
    student_user_id,
    course_id,
    lab_template_id,
    project_id,
    state,
    state_reason,
    ki_resources,
    cleanup_at,
    unfreeze_at,
    frozen_by_user_id,
    frozen_reason,
    student_ssh_key_secret_id,
    checker_ssh_key_secret_id,
    created_at,
    updated_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    COALESCE($15, now()),
    COALESCE($16, now())
)
`

type CreateLabInstanceParams struct {
	ID                    uuid.UUID          `json:"id"`
	StudentUserID         uuid.UUID          `json:"student_user_id"`
	CourseID              uuid.UUID          `json:"course_id"`
	LabTemplateID         uuid.UUID          `json:"lab_template_id"`
	ProjectID             uuid.NullUUID      `json:"project_id"`
	State                 string             `json:"state"`
	StateReason           string             `json:"state_reason"`
	KiResources           []byte             `json:"ki_resources"`
	CleanupAt             pgtype.Timestamptz `json:"cleanup_at"`
	UnfreezeAt            pgtype.Timestamptz `json:"unfreeze_at"`
	FrozenByUserID        uuid.NullUUID      `json:"frozen_by_user_id"`
	FrozenReason          *string            `json:"frozen_reason"`
	StudentSshKeySecretID uuid.NullUUID      `json:"student_ssh_key_secret_id"`
	CheckerSshKeySecretID uuid.NullUUID      `json:"checker_ssh_key_secret_id"`
	CreatedAt             interface{}        `json:"created_at"`
	UpdatedAt             interface{}        `json:"updated_at"`
}

func (q *Queries) CreateLabInstance(ctx context.Context, arg CreateLabInstanceParams) error {
	_, err := q.db.Exec(ctx, createLabInstance,
		arg.ID,
		arg.StudentUserID,
		arg.CourseID,
		arg.LabTemplateID,
		arg.ProjectID,
		arg.State,
		arg.StateReason,
		arg.KiResources,
		arg.CleanupAt,
		arg.UnfreezeAt,
		arg.FrozenByUserID,
		arg.FrozenReason,
		arg.StudentSshKeySecretID,
		arg.CheckerSshKeySecretID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const findActiveLabByStudentAndCourse = `-- name: FindActiveLabByStudentAndCourse :one
SELECT id, student_user_id, course_id, lab_template_id, project_id, state, state_reason, ki_resources, cleanup_at, unfreeze_at, frozen_by_user_id, frozen_reason, student_ssh_key_secret_id, checker_ssh_key_secret_id, created_at, updated_at
FROM lab_instances
WHERE student_user_id = $1
  AND course_id = $2
  AND state NOT IN ('done', 'rejected', 'failed')
ORDER BY created_at DESC, id
LIMIT 1
`

type FindActiveLabByStudentAndCourseParams struct {
	StudentUserID uuid.UUID `json:"student_user_id"`
	CourseID      uuid.UUID `json:"course_id"`
}

func (q *Queries) FindActiveLabByStudentAndCourse(ctx context.Context, arg FindActiveLabByStudentAndCourseParams) (LabInstance, error) {
	row := q.db.QueryRow(ctx, findActiveLabByStudentAndCourse, arg.StudentUserID, arg.CourseID)
	var i LabInstance
	err := row.Scan(
		&i.ID,
		&i.StudentUserID,
		&i.CourseID,
		&i.LabTemplateID,
		&i.ProjectID,
		&i.State,
		&i.StateReason,
		&i.KiResources,
		&i.CleanupAt,
		&i.UnfreezeAt,
		&i.FrozenByUserID,
		&i.FrozenReason,
		&i.StudentSshKeySecretID,
		&i.CheckerSshKeySecretID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLabInstanceByID = `-- name: GetLabInstanceByID :one
SELECT id, student_user_id, course_id, lab_template_id, project_id, state, state_reason, ki_resources, cleanup_at, unfreeze_at, frozen_by_user_id, frozen_reason, student_ssh_key_secret_id, checker_ssh_key_secret_id, created_at, updated_at
FROM lab_instances
WHERE id = $1
`

func (q *Queries) GetLabInstanceByID(ctx context.Context, id uuid.UUID) (LabInstance, error) {
	row := q.db.QueryRow(ctx, getLabInstanceByID, id)
	var i LabInstance
	err := row.Scan(
		&i.ID,
		&i.StudentUserID,
		&i.CourseID,
		&i.LabTemplateID,
		&i.ProjectID,
		&i.State,
		&i.StateReason,
		&i.KiResources,
		&i.CleanupAt,
		&i.UnfreezeAt,
		&i.FrozenByUserID,
		&i.FrozenReason,
		&i.StudentSshKeySecretID,
		&i.CheckerSshKeySecretID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingCleanupLabs = `-- name: ListPendingCleanupLabs :many
SELECT id, student_user_id, course_id, lab_template_id, project_id, state, state_reason, ki_resources, cleanup_at, unfreeze_at, frozen_by_user_id, frozen_reason, student_ssh_key_secret_id, checker_ssh_key_secret_id, created_at, updated_at
FROM lab_instances
WHERE state = 'ready'
  AND cleanup_at <= $1
ORDER BY cleanup_at, id
LIMIT $2
`

type ListPendingCleanupLabsParams struct {
	CleanupAt pgtype.Timestamptz `json:"cleanup_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListPendingCleanupLabs(ctx context.Context, arg ListPendingCleanupLabsParams) ([]LabInstance, error) {
	rows, err := q.db.Query(ctx, listPendingCleanupLabs, arg.CleanupAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LabInstance{}
	for rows.Next() {
		var i LabInstance
		if err := rows.Scan(
			&i.ID,
			&i.StudentUserID,
			&i.CourseID,
			&i.LabTemplateID,
			&i.ProjectID,
			&i.State,
			&i.StateReason,
			&i.KiResources,
			&i.CleanupAt,
			&i.UnfreezeAt,
			&i.FrozenByUserID,
			&i.FrozenReason,
			&i.StudentSshKeySecretID,
			&i.CheckerSshKeySecretID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingUnfreezeLabs = `-- name: ListPendingUnfreezeLabs :many
SELECT id, student_user_id, course_id, lab_template_id, project_id, state, state_reason, ki_resources, cleanup_at, unfreeze_at, frozen_by_user_id, frozen_reason, student_ssh_key_secret_id, checker_ssh_key_secret_id, created_at, updated_at
FROM lab_instances
WHERE state = 'frozen'
  AND unfreeze_at <= $1
ORDER BY unfreeze_at, id
LIMIT $2
`

type ListPendingUnfreezeLabsParams struct {
	UnfreezeAt pgtype.Timestamptz `json:"unfreeze_at"`
	Limit      int32              `json:"limit"`
}

func (q *Queries) ListPendingUnfreezeLabs(ctx context.Context, arg ListPendingUnfreezeLabsParams) ([]LabInstance, error) {
	rows, err := q.db.Query(ctx, listPendingUnfreezeLabs, arg.UnfreezeAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LabInstance{}
	for rows.Next() {
		var i LabInstance
		if err := rows.Scan(
			&i.ID,
			&i.StudentUserID,
			&i.CourseID,
			&i.LabTemplateID,
			&i.ProjectID,
			&i.State,
			&i.StateReason,
			&i.KiResources,
			&i.CleanupAt,
			&i.UnfreezeAt,
			&i.FrozenByUserID,
			&i.FrozenReason,
			&i.StudentSshKeySecretID,
			&i.CheckerSshKeySecretID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLabInstance = `-- name: UpdateLabInstance :one
UPDATE lab_instances
SET project_id = $1,
    state = $2,
    state_reason = $3,
    ki_resources = $4,
    cleanup_at = $5,
    unfreeze_at = $6,
    frozen_by_user_id = $7,
    frozen_reason = $8,
    student_ssh_key_secret_id = $9,
    checker_ssh_key_secret_id = $10,
    updated_at = $11
WHERE id = $12
  AND updated_at <= $11
RETURNING id, student_user_id, course_id, lab_template_id, project_id, state, state_reason, ki_resources, cleanup_at, unfreeze_at, frozen_by_user_id, frozen_reason, student_ssh_key_secret_id, checker_ssh_key_secret_id, created_at, updated_at
`

type UpdateLabInstanceParams struct {
	ProjectID             uuid.NullUUID      `json:"project_id"`
	State                 string             `json:"state"`
	StateReason           string             `json:"state_reason"`
	KiResources           []byte             `json:"ki_resources"`
	CleanupAt             pgtype.Timestamptz `json:"cleanup_at"`
	UnfreezeAt            pgtype.Timestamptz `json:"unfreeze_at"`
	FrozenByUserID        uuid.NullUUID      `json:"frozen_by_user_id"`
	FrozenReason          *string            `json:"frozen_reason"`
	StudentSshKeySecretID uuid.NullUUID      `json:"student_ssh_key_secret_id"`
	CheckerSshKeySecretID uuid.NullUUID      `json:"checker_ssh_key_secret_id"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	ID                    uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateLabInstance(ctx context.Context, arg UpdateLabInstanceParams) (LabInstance, error) {
	row := q.db.QueryRow(ctx, updateLabInstance,
		arg.ProjectID,
		arg.State,
		arg.StateReason,
		arg.KiResources,
		arg.CleanupAt,
		arg.UnfreezeAt,
		arg.FrozenByUserID,
		arg.FrozenReason,
		arg.StudentSshKeySecretID,
		arg.CheckerSshKeySecretID,
		arg.UpdatedAt,
		arg.ID,
	)
	var i LabInstance
	err := row.Scan(
		&i.ID,
		&i.StudentUserID,
		&i.CourseID,
		&i.LabTemplateID,
		&i.ProjectID,
		&i.State,
		&i.StateReason,
		&i.KiResources,
		&i.CleanupAt,
		&i.UnfreezeAt,
		&i.FrozenByUserID,
		&i.FrozenReason,
		&i.StudentSshKeySecretID,
		&i.CheckerSshKeySecretID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
