// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID          uuid.UUID          `json:"id"`
	Kind        string             `json:"kind"`
	ActorUserID uuid.NullUUID      `json:"actor_user_id"`
	SubjectType string             `json:"subject_type"`
	SubjectID   *string            `json:"subject_id"`
	Payload     []byte             `json:"payload"`
	RequestID   *string            `json:"request_id"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
}

type CheckRun struct {
	ID                uuid.UUID          `json:"id"`
	LabInstanceID     uuid.UUID          `json:"lab_instance_id"`
	CheckTemplateID   uuid.UUID          `json:"check_template_id"`
	TriggeredByUserID uuid.NullUUID      `json:"triggered_by_user_id"`
	State             string             `json:"state"`
	Summary           string             `json:"summary"`
	AnsibleStdout     string             `json:"ansible_stdout"`
	AnsibleStats      []byte             `json:"ansible_stats"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type CheckRunStep struct {
	ID         uuid.UUID `json:"id"`
	CheckRunID uuid.UUID `json:"check_run_id"`
	Seq        int32     `json:"seq"`
	TaskName   string    `json:"task_name"`
	Status     string    `json:"status"`
	Expected   []byte    `json:"expected"`
	Actual     []byte    `json:"actual"`
	Message    *string   `json:"message"`
}

type CheckTemplate struct {
	ID              uuid.UUID          `json:"id"`
	Slug            string             `json:"slug"`
	Name            string             `json:"name"`
	LabTemplateID   uuid.NullUUID      `json:"lab_template_id"`
	PlaybookPath    string             `json:"playbook_path"`
	TimeoutSeconds  int32              `json:"timeout_seconds"`
	ExpectedOutcome []byte             `json:"expected_outcome"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Course struct {
	ID         uuid.UUID          `json:"id"`
	ExternalID string             `json:"external_id"`
	Name       string             `json:"name"`
	KiDomainID string             `json:"ki_domain_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type EncryptedSecret struct {
	ID                uuid.UUID          `json:"id"`
	Kind              string             `json:"kind"`
	RefID             string             `json:"ref_id"`
	DekCiphertext     []byte             `json:"dek_ciphertext"`
	DekNonce          []byte             `json:"dek_nonce"`
	PayloadCiphertext []byte             `json:"payload_ciphertext"`
	PayloadNonce      []byte             `json:"payload_nonce"`
	Aad               string             `json:"aad"`
	KekVersion        int32              `json:"kek_version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Enrollment struct {
	UserID       uuid.UUID          `json:"user_id"`
	CourseID     uuid.UUID          `json:"course_id"`
	RoleInCourse string             `json:"role_in_course"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type LabDeployStep struct {
	ID            uuid.UUID          `json:"id"`
	LabInstanceID uuid.UUID          `json:"lab_instance_id"`
	StepName      string             `json:"step_name"`
	Status        string             `json:"status"`
	Attempt       int32              `json:"attempt"`
	LastError     *string            `json:"last_error"`
	Result        []byte             `json:"result"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
}

type LabInstance struct {
	ID                    uuid.UUID          `json:"id"`
	StudentUserID         uuid.UUID          `json:"student_user_id"`
	CourseID              uuid.UUID          `json:"course_id"`
	LabTemplateID         uuid.UUID          `json:"lab_template_id"`
	ProjectID             uuid.NullUUID      `json:"project_id"`
	State                 string             `json:"state"`
	StateReason           string             `json:"state_reason"`
	KiResources           []byte             `json:"ki_resources"`
	CleanupAt             pgtype.Timestamptz `json:"cleanup_at"`
	UnfreezeAt            pgtype.Timestamptz `json:"unfreeze_at"`
	FrozenByUserID        uuid.NullUUID      `json:"frozen_by_user_id"`
	FrozenReason          *string            `json:"frozen_reason"`
	StudentSshKeySecretID uuid.NullUUID      `json:"student_ssh_key_secret_id"`
	CheckerSshKeySecretID uuid.NullUUID      `json:"checker_ssh_key_secret_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type LabTemplate struct {
	ID                     uuid.UUID          `json:"id"`
	Slug                   string             `json:"slug"`
	Name                   string             `json:"name"`
	Description            string             `json:"description"`
	Topology               []byte             `json:"topology"`
	DefaultCleanupAfterS   int32              `json:"default_cleanup_after_s"`
	DefaultFreezeForS      int32              `json:"default_freeze_for_s"`
	DefaultCheckTemplateID uuid.NullUUID      `json:"default_check_template_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
}

type LtiIdentity struct {
	UserID    uuid.UUID          `json:"user_id"`
	Iss       string             `json:"iss"`
	Sub       string             `json:"sub"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Outbox struct {
	ID          int64              `json:"id"`
	Topic       string             `json:"topic"`
	Payload     []byte             `json:"payload"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	Attempts    int32              `json:"attempts"`
}

type Project struct {
	ID                uuid.UUID          `json:"id"`
	KiProjectID       string             `json:"ki_project_id"`
	KiDomainID        string             `json:"ki_domain_id"`
	Name              string             `json:"name"`
	State             string             `json:"state"`
	AllocatedToLabID  uuid.NullUUID      `json:"allocated_to_lab_id"`
	CleanupFailures   int32              `json:"cleanup_failures"`
	LastStateChangeAt pgtype.Timestamptz `json:"last_state_change_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type QuotaCache struct {
	ID        int16              `json:"id"`
	Snapshot  []byte             `json:"snapshot"`
	FetchedAt pgtype.Timestamptz `json:"fetched_at"`
}

type Setting struct {
	Key             string             `json:"key"`
	Scope           string             `json:"scope"`
	ScopeID         string             `json:"scope_id"`
	Value           []byte             `json:"value"`
	UpdatedByUserID uuid.NullUUID      `json:"updated_by_user_id"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	DisplayName  string             `json:"display_name"`
	Email        *string            `json:"email"`
	Role         string             `json:"role"`
	PasswordHash *string            `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
