// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: outbox.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpOutboxAttempts = `-- name: BumpOutboxAttempts :exec
UPDATE outbox
SET attempts = attempts + 1
WHERE id = $1
`

func (q *Queries) BumpOutboxAttempts(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, bumpOutboxAttempts, id)
	return err
}

const fetchOutbox = `-- name: FetchOutbox :many
SELECT id, topic, payload, occurred_at, attempts
FROM outbox
WHERE published_at IS NULL
  AND attempts < $1
ORDER BY id ASC
LIMIT $2
`

type FetchOutboxParams struct {
	MaxAttempts int32 `json:"max_attempts"`
	Limit       int32 `json:"limit"`
}

type FetchOutboxRow struct {
	ID         int64              `json:"id"`
	Topic      string             `json:"topic"`
	Payload    []byte             `json:"payload"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	Attempts   int32              `json:"attempts"`
}

func (q *Queries) FetchOutbox(ctx context.Context, arg FetchOutboxParams) ([]FetchOutboxRow, error) {
	rows, err := q.db.Query(ctx, fetchOutbox, arg.MaxAttempts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FetchOutboxRow{}
	for rows.Next() {
		var i FetchOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.Payload,
			&i.OccurredAt,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox
SET published_at = now()
WHERE id = ANY($1::bigint[])
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, ids)
	return err
}
