// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pool.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const allocateOneFreeProject = `-- name: AllocateOneFreeProject :one
WITH candidate AS (
    SELECT id
    FROM projects AS p
    WHERE p.ki_domain_id = $1
      AND p.state = 'free'
    ORDER BY p.last_state_change_at, p.id
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
UPDATE projects
SET state = 'allocated',
    allocated_to_lab_id = $2,
    last_state_change_at = now()
WHERE id = (SELECT id FROM candidate)
RETURNING id, ki_project_id, ki_domain_id, name, state, allocated_to_lab_id, cleanup_failures, last_state_change_at, created_at
`

type AllocateOneFreeProjectParams struct {
	KiDomainID       string        `json:"ki_domain_id"`
	AllocatedToLabID uuid.NullUUID `json:"allocated_to_lab_id"`
}

func (q *Queries) AllocateOneFreeProject(ctx context.Context, arg AllocateOneFreeProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, allocateOneFreeProject, arg.KiDomainID, arg.AllocatedToLabID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.KiProjectID,
		&i.KiDomainID,
		&i.Name,
		&i.State,
		&i.AllocatedToLabID,
		&i.CleanupFailures,
		&i.LastStateChangeAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, ki_project_id, ki_domain_id, name, state, allocated_to_lab_id, cleanup_failures, last_state_change_at, created_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.KiProjectID,
		&i.KiDomainID,
		&i.Name,
		&i.State,
		&i.AllocatedToLabID,
		&i.CleanupFailures,
		&i.LastStateChangeAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (
    id,
    kind,
    actor_user_id,
    subject_type,
    subject_id,
    payload,
    request_id,
    occurred_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    NULLIF($7, ''),
    COALESCE($8, now())
)
`

type InsertAuditEventParams struct {
	ID          uuid.UUID     `json:"id"`
	Kind        string        `json:"kind"`
	ActorUserID uuid.NullUUID `json:"actor_user_id"`
	SubjectType string        `json:"subject_type"`
	SubjectID   *string       `json:"subject_id"`
	Payload     []byte        `json:"payload"`
	Column7     interface{}   `json:"column_7"`
	OccurredAt  interface{}   `json:"occurred_at"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ID,
		arg.Kind,
		arg.ActorUserID,
		arg.SubjectType,
		arg.SubjectID,
		arg.Payload,
		arg.Column7,
		arg.OccurredAt,
	)
	return err
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (topic, payload, occurred_at)
VALUES ($1, $2, COALESCE($3, now()))
`

type InsertOutboxParams struct {
	Topic      string      `json:"topic"`
	Payload    []byte      `json:"payload"`
	OccurredAt interface{} `json:"occurred_at"`
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox, arg.Topic, arg.Payload, arg.OccurredAt)
	return err
}

const listProjectsByDomain = `-- name: ListProjectsByDomain :many
SELECT id, ki_project_id, ki_domain_id, name, state, allocated_to_lab_id, cleanup_failures, last_state_change_at, created_at
FROM projects
WHERE ki_domain_id = $1
  AND ($2::text IS NULL OR state = $2::text)
ORDER BY created_at, id
`

type ListProjectsByDomainParams struct {
	KiDomainID string  `json:"ki_domain_id"`
	State      *string `json:"state"`
}

func (q *Queries) ListProjectsByDomain(ctx context.Context, arg ListProjectsByDomainParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByDomain, arg.KiDomainID, arg.State)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.KiProjectID,
			&i.KiDomainID,
			&i.Name,
			&i.State,
			&i.AllocatedToLabID,
			&i.CleanupFailures,
			&i.LastStateChangeAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedInsertProject = `-- name: SeedInsertProject :execrows
INSERT INTO projects (
    id,
    ki_project_id,
    ki_domain_id,
    name,
    state,
    allocated_to_lab_id,
    cleanup_failures,
    last_state_change_at,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    COALESCE($8, now()),
    COALESCE($9, now())
)
ON CONFLICT (ki_project_id) DO NOTHING
`

type SeedInsertProjectParams struct {
	ID                uuid.UUID     `json:"id"`
	KiProjectID       string        `json:"ki_project_id"`
	KiDomainID        string        `json:"ki_domain_id"`
	Name              string        `json:"name"`
	State             string        `json:"state"`
	AllocatedToLabID  uuid.NullUUID `json:"allocated_to_lab_id"`
	CleanupFailures   int32         `json:"cleanup_failures"`
	LastStateChangeAt interface{}   `json:"last_state_change_at"`
	CreatedAt         interface{}   `json:"created_at"`
}

func (q *Queries) SeedInsertProject(ctx context.Context, arg SeedInsertProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, seedInsertProject,
		arg.ID,
		arg.KiProjectID,
		arg.KiDomainID,
		arg.Name,
		arg.State,
		arg.AllocatedToLabID,
		arg.CleanupFailures,
		arg.LastStateChangeAt,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET state = $2,
    allocated_to_lab_id = $3,
    cleanup_failures = $4,
    last_state_change_at = $5
WHERE id = $1
  AND last_state_change_at < $5
RETURNING id, ki_project_id, ki_domain_id, name, state, allocated_to_lab_id, cleanup_failures, last_state_change_at, created_at
`

type UpdateProjectParams struct {
	ID                uuid.UUID          `json:"id"`
	State             string             `json:"state"`
	AllocatedToLabID  uuid.NullUUID      `json:"allocated_to_lab_id"`
	CleanupFailures   int32              `json:"cleanup_failures"`
	LastStateChangeAt pgtype.Timestamptz `json:"last_state_change_at"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.State,
		arg.AllocatedToLabID,
		arg.CleanupFailures,
		arg.LastStateChangeAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.KiProjectID,
		&i.KiDomainID,
		&i.Name,
		&i.State,
		&i.AllocatedToLabID,
		&i.CleanupFailures,
		&i.LastStateChangeAt,
		&i.CreatedAt,
	)
	return i, err
}
