// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

type Querier interface {
	AllocateOneFreeProject(ctx context.Context, arg AllocateOneFreeProjectParams) (Project, error)
	GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error
	InsertOutbox(ctx context.Context, arg InsertOutboxParams) error
	ListProjectsByDomain(ctx context.Context, arg ListProjectsByDomainParams) ([]Project, error)
	SeedInsertProject(ctx context.Context, arg SeedInsertProjectParams) (int64, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
}

var _ Querier = (*Queries)(nil)
