// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: quota_cache.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getQuotaCache = `-- name: GetQuotaCache :one
SELECT snapshot, fetched_at
FROM quota_cache
WHERE id = 1
`

type GetQuotaCacheRow struct {
	Snapshot  []byte             `json:"snapshot"`
	FetchedAt pgtype.Timestamptz `json:"fetched_at"`
}

func (q *Queries) GetQuotaCache(ctx context.Context) (GetQuotaCacheRow, error) {
	row := q.db.QueryRow(ctx, getQuotaCache)
	var i GetQuotaCacheRow
	err := row.Scan(&i.Snapshot, &i.FetchedAt)
	return i, err
}

const upsertQuotaCache = `-- name: UpsertQuotaCache :exec
INSERT INTO quota_cache (id, snapshot, fetched_at)
VALUES (1, $1, now())
ON CONFLICT (id) DO UPDATE
SET snapshot = EXCLUDED.snapshot,
    fetched_at = now()
`

func (q *Queries) UpsertQuotaCache(ctx context.Context, snapshot []byte) error {
	_, err := q.db.Exec(ctx, upsertQuotaCache, snapshot)
	return err
}
