// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: secrets.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

// #nosec G101 -- generated SQL references encrypted_secrets table; no credentials.
const deleteEncryptedSecret = `-- name: DeleteEncryptedSecret :exec
DELETE FROM encrypted_secrets
WHERE id = $1
`

func (q *Queries) DeleteEncryptedSecret(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEncryptedSecret, id)
	return err
}

// #nosec G101 -- generated SQL references encrypted_secrets table; no credentials.
const getEncryptedSecretByID = `-- name: GetEncryptedSecretByID :one
SELECT id, kind, ref_id, dek_ciphertext, dek_nonce, payload_ciphertext, payload_nonce, aad, kek_version, created_at
FROM encrypted_secrets
WHERE id = $1
`

func (q *Queries) GetEncryptedSecretByID(ctx context.Context, id uuid.UUID) (EncryptedSecret, error) {
	row := q.db.QueryRow(ctx, getEncryptedSecretByID, id)
	var i EncryptedSecret
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.RefID,
		&i.DekCiphertext,
		&i.DekNonce,
		&i.PayloadCiphertext,
		&i.PayloadNonce,
		&i.Aad,
		&i.KekVersion,
		&i.CreatedAt,
	)
	return i, err
}

// #nosec G101 -- generated SQL references encrypted_secrets table; no credentials.
const insertEncryptedSecret = `-- name: InsertEncryptedSecret :one
INSERT INTO encrypted_secrets (
    id,
    kind,
    ref_id,
    dek_ciphertext,
    dek_nonce,
    payload_ciphertext,
    payload_nonce,
    aad,
    kek_version,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    COALESCE($10, now())
)
RETURNING id, kind, ref_id, dek_ciphertext, dek_nonce, payload_ciphertext, payload_nonce, aad, kek_version, created_at
`

type InsertEncryptedSecretParams struct {
	ID                uuid.UUID   `json:"id"`
	Kind              string      `json:"kind"`
	RefID             string      `json:"ref_id"`
	DekCiphertext     []byte      `json:"dek_ciphertext"`
	DekNonce          []byte      `json:"dek_nonce"`
	PayloadCiphertext []byte      `json:"payload_ciphertext"`
	PayloadNonce      []byte      `json:"payload_nonce"`
	Aad               string      `json:"aad"`
	KekVersion        int32       `json:"kek_version"`
	CreatedAt         interface{} `json:"created_at"`
}

func (q *Queries) InsertEncryptedSecret(ctx context.Context, arg InsertEncryptedSecretParams) (EncryptedSecret, error) {
	row := q.db.QueryRow(ctx, insertEncryptedSecret,
		arg.ID,
		arg.Kind,
		arg.RefID,
		arg.DekCiphertext,
		arg.DekNonce,
		arg.PayloadCiphertext,
		arg.PayloadNonce,
		arg.Aad,
		arg.KekVersion,
		arg.CreatedAt,
	)
	var i EncryptedSecret
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.RefID,
		&i.DekCiphertext,
		&i.DekNonce,
		&i.PayloadCiphertext,
		&i.PayloadNonce,
		&i.Aad,
		&i.KekVersion,
		&i.CreatedAt,
	)
	return i, err
}
