// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: settings.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const listSettings = `-- name: ListSettings :many
SELECT key, scope, scope_id, value, updated_by_user_id, updated_at
FROM settings
WHERE ($1::text IS NULL OR scope = $1::text)
  AND ($2::text IS NULL OR scope_id = $2::text)
ORDER BY scope, scope_id, key
`

type ListSettingsParams struct {
	Scope   *string `json:"scope"`
	ScopeID *string `json:"scope_id"`
}

func (q *Queries) ListSettings(ctx context.Context, arg ListSettingsParams) ([]Setting, error) {
	rows, err := q.db.Query(ctx, listSettings, arg.Scope, arg.ScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Setting{}
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.Key,
			&i.Scope,
			&i.ScopeID,
			&i.Value,
			&i.UpdatedByUserID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveSetting = `-- name: ResolveSetting :one
SELECT key, scope, scope_id, value, updated_by_user_id, updated_at
FROM settings
WHERE key = $1
  AND (
    (scope = 'per_lab_template' AND scope_id = COALESCE($2::text, '__none__'))
    OR (scope = 'per_course' AND scope_id = COALESCE($3::text, '__none__'))
    OR (scope = 'global' AND scope_id = '')
  )
ORDER BY CASE scope
    WHEN 'per_lab_template' THEN 1
    WHEN 'per_course' THEN 2
    ELSE 3
END
LIMIT 1
`

type ResolveSettingParams struct {
	Key           string  `json:"key"`
	LabTemplateID *string `json:"lab_template_id"`
	CourseID      *string `json:"course_id"`
}

func (q *Queries) ResolveSetting(ctx context.Context, arg ResolveSettingParams) (Setting, error) {
	row := q.db.QueryRow(ctx, resolveSetting, arg.Key, arg.LabTemplateID, arg.CourseID)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Scope,
		&i.ScopeID,
		&i.Value,
		&i.UpdatedByUserID,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSetting = `-- name: UpsertSetting :one
INSERT INTO settings (
    key,
    scope,
    scope_id,
    value,
    updated_by_user_id,
    updated_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    COALESCE($6, now())
)
ON CONFLICT (key, scope, scope_id) DO UPDATE
SET value = EXCLUDED.value,
    updated_by_user_id = EXCLUDED.updated_by_user_id,
    updated_at = EXCLUDED.updated_at
RETURNING key, scope, scope_id, value, updated_by_user_id, updated_at
`

type UpsertSettingParams struct {
	Key             string        `json:"key"`
	Scope           string        `json:"scope"`
	ScopeID         string        `json:"scope_id"`
	Value           []byte        `json:"value"`
	UpdatedByUserID uuid.NullUUID `json:"updated_by_user_id"`
	UpdatedAt       interface{}   `json:"updated_at"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) (Setting, error) {
	row := q.db.QueryRow(ctx, upsertSetting,
		arg.Key,
		arg.Scope,
		arg.ScopeID,
		arg.Value,
		arg.UpdatedByUserID,
		arg.UpdatedAt,
	)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Scope,
		&i.ScopeID,
		&i.Value,
		&i.UpdatedByUserID,
		&i.UpdatedAt,
	)
	return i, err
}
