// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, display_name, email, role, password_hash, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.Role,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByLTI = `-- name: GetUserByLTI :one
SELECT u.id, u.display_name, u.email, u.role, u.password_hash, u.created_at
FROM users u
JOIN lti_identities li ON li.user_id = u.id
WHERE li.iss = $1
  AND li.sub = $2
`

type GetUserByLTIParams struct {
	Iss string `json:"iss"`
	Sub string `json:"sub"`
}

func (q *Queries) GetUserByLTI(ctx context.Context, arg GetUserByLTIParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLTI, arg.Iss, arg.Sub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.Role,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const insertUserFromLaunch = `-- name: InsertUserFromLaunch :one
INSERT INTO users (
    id,
    display_name,
    email,
    role,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    COALESCE($5, now())
)
RETURNING id, display_name, email, role, password_hash, created_at
`

type InsertUserFromLaunchParams struct {
	ID          uuid.UUID   `json:"id"`
	DisplayName string      `json:"display_name"`
	Email       *string     `json:"email"`
	Role        string      `json:"role"`
	CreatedAt   interface{} `json:"created_at"`
}

func (q *Queries) InsertUserFromLaunch(ctx context.Context, arg InsertUserFromLaunchParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUserFromLaunch,
		arg.ID,
		arg.DisplayName,
		arg.Email,
		arg.Role,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.Role,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const listCourseRolesByUser = `-- name: ListCourseRolesByUser :many
SELECT course_id, role_in_course
FROM enrollments
WHERE user_id = $1
`

type ListCourseRolesByUserRow struct {
	CourseID     uuid.UUID `json:"course_id"`
	RoleInCourse string    `json:"role_in_course"`
}

func (q *Queries) ListCourseRolesByUser(ctx context.Context, userID uuid.UUID) ([]ListCourseRolesByUserRow, error) {
	rows, err := q.db.Query(ctx, listCourseRolesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCourseRolesByUserRow{}
	for rows.Next() {
		var i ListCourseRolesByUserRow
		if err := rows.Scan(&i.CourseID, &i.RoleInCourse); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserFromLaunch = `-- name: UpdateUserFromLaunch :one
UPDATE users
SET display_name = $1,
    email = $2,
    role = $3
WHERE id = $4
RETURNING id, display_name, email, role, password_hash, created_at
`

type UpdateUserFromLaunchParams struct {
	DisplayName string    `json:"display_name"`
	Email       *string   `json:"email"`
	Role        string    `json:"role"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserFromLaunch(ctx context.Context, arg UpdateUserFromLaunchParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserFromLaunch,
		arg.DisplayName,
		arg.Email,
		arg.Role,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.Role,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const upsertLTIIdentity = `-- name: UpsertLTIIdentity :exec
INSERT INTO lti_identities (
    user_id,
    iss,
    sub,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    COALESCE($4, now())
)
ON CONFLICT (iss, sub) DO UPDATE
SET user_id = EXCLUDED.user_id
`

type UpsertLTIIdentityParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	Iss       string      `json:"iss"`
	Sub       string      `json:"sub"`
	CreatedAt interface{} `json:"created_at"`
}

func (q *Queries) UpsertLTIIdentity(ctx context.Context, arg UpsertLTIIdentityParams) error {
	_, err := q.db.Exec(ctx, upsertLTIIdentity,
		arg.UserID,
		arg.Iss,
		arg.Sub,
		arg.CreatedAt,
	)
	return err
}
